### ISSUE TITLE
Remaining website redesign snag list

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#1026]
## The Chore

What we need to achieve and who for

## Tasks

- [x] Change "insights" to "articles" ... both the titel and the tags
- [x] Update the community strapline to "Learn, Test, Govern - where do you fit in the Vega Ecosystem?"
- [x] Put the footer back in
- [x] Fix the twitter last tweet thing
- [x] Replace "GET A VEGA WALLET" on teh governance section with "Stake VEGA".  include text saying "Stake your VEGA tokens on the governance site to be eligible to vote, note you will need to get a wallet (link to wallet page) to do this. Clicking the box should send you to https://governance.vega.xyz/token/associate

**Comment by JonRay15** [comment]
The articles are still tagged as "insights" on the actual articles themselves.

![Image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/de41ac51-3c9b-44fb-88f1-d6d46b66caec)

**Comment by JonRay15** [comment]
The community tag line isnt changed

![Image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/5cdf5331-e853-4d16-8067-9a61723a4bcd)
