### ISSUE TITLE
Final Legal review on website content

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#1067]
## The Chore

Dave to do a final runthrough to ensure he is happy with all pages

## Tasks

- [ ] Get Dave to do a review once we're done with Palazzo changes
- [ ] Ensure it covers both the blocked and unblocked versions
- [ ] Make any adjustments
