### ISSUE TITLE
Add thousand and millions formatting to stake numbers

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#1071]
## The Chore

Currently all the markets are in USDT, so for now the quantum formatting in #707 seems less important than just getting user-friendly numbers in USDT terms.  Quantum formatting is only really useful if we have markets settling in things like BTC and ETH where we'd need to know how many DP to show to capture those numbers properly. 

For now in USDT terms we should simply do as below, and we can enhance this later if we get markets in other currencies. 

These should apply to both target stake and supplied stake which are denoted as X in the below.

## Tasks

- [ ] If X < 100 show the full number with 2 DP
- [ ] If 100 < X < 1000 show the full number with 0 DP
- [ ] If 1,000 < X < 1,000,000 divide by 1,000 and show with a K suffix and 2 DP, ie. 1453 = 1.45K
- [ ] If 1,000,000 < X divide by 1,000,000 and show with M suffix and 2 DP, ie. 1,876,635 = 1.88M

## Additional details / background info

The above could equally be summarised as "show 3 significant figures and with appropriate K and M suffixes" .... dunno why I broke it down so explicitly!
