### ISSUE TITLE
Changes for blocked countries

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega.xyz#1099]
- Blocked by requirements
- Blocked by devops

## The Chore

Some changes to what we display and where given that we don't want to entirely block vega.xyz in restricted countries

## Tasks
- [ ] Use env var to control content for restricted pages/components
- [ ] Update CI to build the site twice once restricted once not restriced
- [ ] Update hosting to serve different versions depending on users location @daniel1302 

### Content changes
- [ ] Remove market tiles from home page
- [ ] Add a warning banner (text TBD)
- [ ] Hide link to Console
- [ ] Block the liquidity dashboard page

## Additional details / background info

Broken out from https://github.com/vegaprotocol/devops-infra/issues/2101

Recent thread on this work here: https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1700502877390569

**Comment by daniel1302** [comment]
We decided to create an endpoint that can be queried by the HTTP call before the website is generated. 

Then when the user opens the page, there is a background query to the service that allows/blocks the website. Based on the response we decide what to show/hide from the user.

<img width="623" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1239637/9ac69f9e-9ec1-4eda-8528-6040afec4897">

**Comment by mattrussell36** [comment]
Lets look into generating two separate versions of the pages that require changes and redirecting accordingly

**Comment by mattrussell36** [comment]
I think a simple approach here that won't require javascript will be to generate two versions of the site, one restricted and one unrestricted, we then just serve from a different folder depending on the users location.

This would look like:
- Use an env variable, GATSBY_RESTRICTED to control the content where needed
- Build the site twice, `GATSBY_RESTRICTED=true npx gatsby build` and just `npx gatsby build` for unrestricted
- Host the sites in two different directories
- Serve the correct site using some middleware to detect the country

**Comment by edd** [comment]
Done
