### ISSUE TITLE
Add Ecosystem homepage for partnerships

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/vega.xyz#1117]
We need to add the Hummgbot logo somewhere on the website. Reminder to Rebecca.

## Tasks

- [ ] Overhaul apps and tools so it is Ecoystem Home
- [ ] Rework the filters so we have fewer filters for the apps and instead a filter for integrations etc
  - [ ] Integrations
  - [ ] Wallets
  - [ ] dApps
  - [ ] Analytics
  - [ ] Validators
  - [ ] Build on Vega
- [ ] Add logos with the projects below and some blurb on a hover
- [ ] Add some more tiles for the stuff like build etc which dont have a tile yet
- [ ] Add the top 3 to a section on the homepage
- [ ] Add a disclaimer at the top when the Integrations filter is applied which says "Integrations do not necessarily imply any official partnership or relationship between Vega Protocol and the integration listed".

#### Logo

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/6720c2ea-64a5-4cd4-9680-fd6e98fc3847)

#### Blurb

Vega supports bridging of any ERC20 token onto the network, so long as that token has been proposed and approved via on-chain governance.  The protocol can also source oracle data from any Ethereum RPC.

#### Tile link

https://ethereum.org/

#### Logo (might want to get this approved with them)

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/92e4883e-ed50-4ed7-9ba8-20eb9440671a)

or 

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/e383b8f5-d4e6-4ee4-9795-2c2bf1b1527d)

Depending on which looks better on website

#### Blurb

Run pre-built automated strategies or compose your own with Hummingbot on Vega.

#### Tile link

https://hummingbot.org/

#### Logo

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/7653a90b-9c89-4865-b86c-dfe80055f2a7)

#### Blurb

Any price feed available via Chainlink can be used to drive a market on the network through the protocol's flexible Ethereum oracles framework.

#### Tile link

https://chain.link/

#### Logo

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/1332cf01-9e38-445d-b1ed-25b3691e190d)

#### Blurb

The Vega network can source prices from any Uniswap pool by using this [community created smart contract](https://github.com/jeremyletang/uniswap_price_source) during market creation.

#### Tile link

https://app.uniswap.org/

#### Logo

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/6284eefc-be3e-4f19-80f7-e19efcd6b89c)

#### Blurb

TradingView powered charts available in some versions of Console alongside Vega's own open source chart software.

#### Tile link

https://www.tradingview.com/

#### Logo

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/4b16369b-ab11-4e7c-b86a-f12b375b5f26)

#### Blurb

Connect to Console or Governance apps using the Vega MetaMask Snap for quick and pain free onboarding to the Vega network.

#### Tile link

https://metamask.io/

#### Logo

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/a9bd8d97-fefd-4a1f-8873-a9183a35ebb3)

#### Blurb

Pyth price data feeds can be pushed to a contract on Ethereum, Gnosis or Arbitrum chains and once available can be consumed by the protocol's data sourcing framework.

#### Tile link

https://pyth.network/

#### Logo

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/7b6800d2-0990-43a6-8543-558db970417b)

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/ecf73a5f-081b-4d20-9c5c-9f2e3b38f419)

#### Blurb

Gnosis offers low fee, high efficiency infrastructure for provision of pricing feeds as part of Vega's Ethereum L2 oracles framework.

#### Tile link

https://www.gnosis.io/

#### Logo

![image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/bcaf1c32-c750-4bc7-86d4-7e556ed37fff)

#### Blurb

Arbitrm offers low fee, high efficiency infrastructure for provision of pricing feeds as part of Vega's Ethereum L2 oracles framework.

#### Tile link

https://arbitrum.io/

#### Logo

<img width="115" alt="image" src="https://github.com/vegaprotocol/vega.xyz/assets/89918817/7f4e5a8c-08f2-44c8-a983-8c4ee2de4c23">

#### Blurb

Visit the Governance app to browse the validators on the Vega network, stake your VEGA tokens, and participcate in Governance

#### Tile link

https://governance.vega.xyz/

#### Logo

![Image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/183b213b-c88e-4143-812b-5ba86bd664e6)

#### Blurb

Visit the Vega dashboard on Dune Analytics to explore key metrics for the network.

#### Tile link

https://dune.com/vega_protocol/analytics

#### Logo

![Image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/b9a5a6be-9d1a-49bf-8936-05bc3a7508b0)

#### Blurb

Visit the Vega dashboard on Defi Llama to explore on chain metrics for the network.

#### Tile Link

https://defillama.com/protocol/vega-protocol

**Comment by barnabee** [comment]
- [ ] Ethereum wording should mention oracle data sourcing too
- [ ] Pyth wording is inaccurate and implies that EVM data sourcing is powered by Pyth, where actually Pyth is an option for EVM RPC (and Ethereum mainnet) data sourcing when and if Pyth data is pushed to a contract on the relevant chain _and_ markets are created or updated to reference the Pyth contract.

**Comment by barnabee** [comment]
I'd suggest a little info box about the results when the integrations filter is selected (like the one for the governance filter) that reminds people that these are integrations between the Vega network, dapps, or some specific markets and other networks/projects/protocols/software and that they don't necessarily imply official partnerships or permission.

**Comment by rebeccajsimmonds** [comment]
@JonRay15 can you confirm the categorisation of each of the following (they can be more than 1):

Ethereum -> Integration
Hummingbot -> build?
Chainlink -> analytics
Uniswap -> d'apps?
Trading view -> analytics
Metamask -> wallets
Pyth -> integrations
Gnosis -> integrations
Arbiturm -> ingtegrations
Validators -> d'app?
