### ISSUE TITLE
Add browser wallet to Apps page

### ISSUE THREAD

**Issue by goslingo** [vegaprotocol/vega.xyz#1119]
## Story

I want to see that there is a browser wallet available on the Apps page

## Tasks

- [ ] Add a new tile
- [ ] Need a coloured icon from David
- [ ] Call it simply "Vega Wallet" and display it first
- [ ] The strapline can mirror the chromestore: "Connect to Vega dApps and sign transactions from your browser on the Vega network."

**Comment by bigfandavid** [comment]
Hi @rebeccajsimmonds @JonRay15 

Please find attached a screenshot of the three wallet icons next to each other for context. There is a new Desktop Wallet icon + an icon to fill the currently empty space of the CLI wallet.

Also attaching png files should these be good to go so you can get them on the site.

Any questions, or comments, please let me know!

Best wishes,
David

[
![Browser Wallet Icon](https://github.com/vegaprotocol/vega.xyz/assets/113683891/44eb5ab4-981a-43e7-9537-d441fbefd19c)
![CLI Wallet Icon](https://github.com/vegaprotocol/vega.xyz/assets/113683891/05d83152-891b-40a5-97b5-3ae4116b5056)
<img width="1052" alt="Screenshot 2024-01-16 at 15 56 08" src="https://github.com/vegaprotocol/vega.xyz/assets/113683891/e073e91c-2894-4a2e-b867-7495e37b70b9">
](url)

**Comment by rebeccajsimmonds** [comment]
@edd Would you be able update the website with these new tiles?
