### ISSUE TITLE
Consistent header alignment across all pages

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#1138]
## The Chore

Its annoying they are not the same.

## Tasks

- [ ] Identify the centre aligned stuff
- [ ] Make it left aligned
- [ ] Ensure its all the same font size
- [ ] Ensure they're not CAPITALISED
