### ISSUE TITLE
Review of key features

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#1139]
## Tasks

- [ ] Review te key features on homepage for the Palazzo relevance (Isolated margin, Teams? Oracles?)
- [ ] Update the "view all" link to be "learn more" and send you to the new docs home (Tom's ones)
- [ ] Remove the Key concepts page as its now confusing and outdated
