### ISSUE TITLE
Edit Partners and Backers information

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/vega.xyz#1159]
```[tasklist]
### Tasks
- [ ] https://github.com/vegaprotocol/vega.xyz/issues/1160
- [ ] Remove the 'what they say' link from Xpring
- [ ] Add a second 'what they say' link to Arrington and link here https://www.arringtoncapital.com/wp-content/uploads/2021/06/vega_the_space_race_for_open_markets.pdf
- [ ] Add a second 'what they say' link to Greenfield One and link to this 'https://medium.com/greenfield-one/vega-protocol-fair-access-to-efficient-resilient-derivatives-markets-dba11fe281aa
```
