### ISSUE TITLE
Identify updates and additions required for trading launch

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#184]
## Story

As a team
We want to get an understanding of everything that needs to be added/updated on vega.xyz on or by the day that trading is enabled
So that we can plan our work effectively and ensure we deliver on time and meet expectations

## Tasks

- [x] Review [proof of concept](https://drive.google.com/file/d/13b_RJvWQSWP83q89KZEOEpWd5CbTe1np/view) video
- [x] Ask Oli for the link to his implementation of the concept [it's no longer online, but we do still have some parallax code available for .xyz]
- [x] Add missing pages
   - [x] Careers
- [x] Add forthcoming pages (validators, rewards…?)
- [x] Check existing pages are up to date
- [x] Highlight mentions of mainnet, testnet, coming soon that will need to be changed
- [x] Change docs links to mainnet
- [ ] Research what other people do to JAZZ UP their sites
- [x] Collate a list of changes we'd like to implement and release when trading is enabled
- [x] Review and agree with the team
- [x] Review and agree with key stakeholders
- [ ] Create and prioritise cards on the backlog for the work

How can we make pages come to life, be exciting and lively? Animation, video, parallax, transitioning stuff in… steal ideas from Apple!

Current expected date to announce trading enabled is **3rd November**

Slack thread re getting other team's thoughts on what will need to be updated when we have launched trading https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1662393593998179

**Comment by neildawson** [comment]
Prioritised list here: https://miro.com/app/board/o9J_lnkofoQ=/?moveToWidget=3458764535671634260&cot=10
