### ISSUE TITLE
Add threshold information to governance lifecycle

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#190]
## Story

As a user 
I want to understand what thresholds there are in order to make a proposal and how this helps contributors have the greatest say
So that I can be assured there is a reasonable gateway in place to make a proposal, and I know what that is before trying to make one myself

## Acceptance Criteria

- [ ] For the https://vega.xyz/governance page, we've explained that in order to make a proposal, you need a minimal proposer balance (or similar) and linked to https://explorer.vega.xyz/network-parameters
- [ ] We've introduced the concept of thresholds to the lifecycle steps on the governance page
- [ ] We have added Network parameters on https://vega.xyz/market-creation
   - [ ] Get voting: replace "1 $VEGA" with [network parameter: ] 
   - [ ] Submit your proposal: "Anyone with the minimum number of [network parameter: ] VEGA tokens" 
   - [ ] Launch market: Add "[network parameter: governance.proposal.market.requiredMajority] of token holders will need to vote on your proposal, with a [network parameter: ] majority favour required to pass."

## Tasks

- [X] Use network parameter component to embed thresholds in governance tutorials in docs
- [X] Look at other touchpoints for opportunities to embed
- [X] Understand how Edd has built the component used on docs / the variables it covers
- [x] Design component to show network parameter on .xyz (including if we still use an emoji) consistent to the doc site
- [x] Team design review
- [x] Update copy on governance lifecycle page to explain proposer balance and link to network params:
  - [x] In phase 3, insert the following before the final sentence:
  > The number of tokens needed to make a proposal differs by proposal type, for example [governance.proposal.market.minProposerBalance] for a new market proposal.
  - [x] In phase 4, replace the sentence starting "Note, each public key…" with the following:
  > The number of tokens needed to vote differs by proposal type, for example [governance.proposal.market.minVoterBalance] for a new market proposal. Each public key is eligible for one vote.
  - [x] In phase 5, replace the description with the following:
  > If a proposal receives enough participation and reaches the majority threshold within the voting period, the change is automatically enacted (with the exception of free form proposals). The thresholds differ by proposal type, for example a new market proposal requires participation of [governance.proposal.market.requiredParticipation] and a majority of [governance.proposal.market.requiredMajority].
- [x] Implement changes (including integrations with network parameters) on .xyz for market creation page: 
  - [x] In phase 3, insert the following within this sentence "Anyone with **governance.proposal.market.minProposerBalance**  $VEGA tokens who has staked to a validator, can submit a new market proposal." 
  - [x] In phase 4 insert the following within this sentence "Note, each public key with a minimum of **governance.proposal.market.minVoterBalance** $VEGA gets just one vote per proposal."
- [x] Implement any changes identified to forum content (Neil / Calum)
- [x] Create tickets in the relevant backlogs for changes identified for Console, Block Explorer or Token Site (Neil / Calum) 
- [x] Team Testing
- [ ] Share with Vega
- [ ] Release

![Image](https://user-images.githubusercontent.com/47143694/190851576-6dc72fc7-b4b6-4b4c-a954-33a5c35f643f.png)

**Comment by pennyandrews** [comment]
Neil:

Relevant GitHub issue: https://github.com/vegaprotocol/documentation/issues/213
Background info: https://vegaprotocol.slack.com/archives/C03HG3YNNNM/p1662568410890859

**Comment by pennyandrews** [comment]
Joëlle:

What do you think of one of the attached approaches? Related Figma frame is [here](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=755%3A27099) → 

![Image](https://user-images.githubusercontent.com/47143694/190851613-e62b2a2d-ef18-4449-b0c4-008a41bb7b60.png)

In the Figma, on the left is one of the suggestions shown within the accordion and also in a callout. 
Do you think this component could exist in callouts too? 
To the right is light mode.

If we wanted to use colour to make it more prominent - pink felt like a relevant option as it works across light and dark mode, the inconsistency here being that in dark mode the select text highlight is pink but in light mode it is yellow.

There are options of dashed or dotted underlines, a background highlight and icons. Did some reading and it seems that as discussed, dashed / dotted underlines indicate "text that shows a tooltip on hover / reveals more information". The use of a question mark or info icon seems to be another pattern. 

Assumed in the tooltip there would be formatting of eg. long numbers but that's a separate discussion / task. 

I know a tooltip might not be part of this task in the first instance. But I think conceptually the styling logic still applies in that there is more info directly related to the link (more so than a normal link that goes out to another webpage)

Let me know your thoughts!

**Comment by pennyandrews** [comment]
Joëlle:

Have created this as a point of conversation for link styles, at the bottom is the recommendation based off our chat with two different hover options (+ option with tooltip).

![Image](https://user-images.githubusercontent.com/47143694/190851645-bbe7d44c-3a60-4a6e-97e5-d2a67762298e.png)

[Figma link](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=777%3A28106) → 

The active / visited states I thought made sense to define once we chat with Oli / David.

Light mode I can spec out once dark mode is decided (for this network parameter component) - is essentially inverting and adjusting the grey to work on the light background.

**Comment by neildawson** [comment]
@goslingo You thought we might be able to pinch some code from docs since both sites use React. I think this is [the code for the network parameter component in docs](https://github.com/vegaprotocol/documentation/blob/main/src/components/NetworkParameter.js). Edd made this so could answer questions.

I wrote a list of all the ways this can be configured in #254. Based on the parameters we need to embed on the market creation page (see the checklist in this ticket) we'll need at least this functionality on xyz:

- the governance token formatter
- the percentage formatter
- suffixes

Also @joellecharlotte I noticed we have this mouseover box on [the contributors page](https://vega.xyz/community/contributors). I wonder if we want to use one style for both of these and we could add it to the design system.

![Image](https://user-images.githubusercontent.com/1080322/191715189-8de2d1a7-000d-4af9-b12d-63b2bf0c8141.png)

**Comment by joellecharlotte** [comment]
@neildawson good spot. I think having a unified tooltip is a good idea as opposed to introducing a new design. I've mocked it up in the context of the network parameter component below the original design for comparison.

@goslingo what is the font size of the "View on Github" link? If it is 14px that would match the size of the text in the network parameter which would be good as it's our now renamed "Body S" text style which could have a respective "Link S" style.

![Image](https://user-images.githubusercontent.com/113684458/191945480-a648870f-9920-4949-99b1-dc97d7f20ed7.png)

**Comment by neildawson** [comment]
Both look good!

One thing I hadn't considered: on the contributors page, you can click on the tooltip box, i.e. it doesn't disappear when you move the mouse away, so long as the mouse is still over the tooltip. I think it's fine for that behaviour to remain here, even though we don't have links in this tooltip. Just raising in case anybody thinks this might complicate things. 

Also that reminds me, Candida suggested we remove the word "number" as network parameters aren't always numbers.

**Comment by neildawson** [comment]
Oh and a note for @goslingo that we should match the capitalisation of the parameter names from [this list](https://lb.testnet.vega.xyz/network/parameters) (i.e. camel case, with the first letter lowercase). For some reason the first letters on [the network parameters page](https://explorer.vega.xyz/network-parameters) are capitalised, which is a bit annoying as they're case sensitive.

**Comment by pennyandrews** [comment]
If it's an option @joellecharlotte I'd be inclined to go for the first one with round corners as I feel like we use the second one for lots of things on the site that are clickable like buttons and cards and so this could be misleading for something that is just information??? If you guys know better then feel free to ignore me

**Comment by neildawson** [comment]
Yeah good point @pennyandrews. I agree. In that case, perhaps the task to standardise the pattern should wait until we make updates to the contributors page.

**Comment by joellecharlotte** [comment]
@pennyandrews I'm sold on this logic, let's defer this as a larger task to look at tooltips across the site and question the various patterns for cards vs tooltips vs buttons when used like this.

**Comment by neildawson** [comment]
@ckpringle @goslingo I've added the required changes for the governance page as tasks on this ticket, rather than making a new ticket, to keep all the network parameter stuff together. Oli, let me know if the descriptions need more clarity.
