### ISSUE TITLE
Trading launch announcement takeover

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#191]
**_This sprint Rebecca to help get the details of the changes needed to content for the announcement, ready to make the changes next sprint._**

## Story

As a team
We want to create an immersive website takeover to announce the launch of trading on Vega's mainnet
So that everyone that visits the site knows that they could now trade and is given clear CTA's for where to go to get started

## Tasks

- [X] Start to get an idea what the content might be for the keynote presentation (session with Barney and Nissa)
- [X] Team immersion session on POAPs to helps us understand what's possible 
- [X] Establish if we think we can deliver it or need to bring in additional resources
- [X] Flesh out idea and visual approach
- [X] Call with Nissa and Edo on Friday to discuss and decide approach / budget
- [X] Discussion on how we want to do this
- [X] Sketch out what needs to be covered in the simplified takeover
- [X] Design takeover
- [X] Mock up / explore options for homepage revamp to review and discuss with the team
- [ ] Chase feedback - give them a deadline
- [x] Create script / content including the timeline text
- [x] Create responsive versions of design
- [ ] Give it an ending - what are the calls to action?
- [ ] Ensure it's working on mobile

## Background

Conclusions from the call with Nissa:
- We will stick with a takeover, but simplified more to the announcement end of the scale with no video
- We will look to have some kind of revamped homepage and incorporate animations and parallax type effects to give the feel of the site (and Vega) 'coming to life' now trading is enabled

**Comment by ckpringle** [comment]
@bigfandavid @goslingo how valuable is the "second part" of this takeover given that we've just updated the roadmap with similar content. Is there a way to hand over 'gracefully' from the trading takeover as is to the roadmap on the landing page? Does the takeover feel "enough" without the second part or does it land flat.

**Comment by rebeccajsimmonds** [comment]
I've marked this blocked until we get agreement from Barney and Ramsey

**Comment by pennyandrews** [comment]
Decision made and communicated by Nissa that this work will not go ahead and instead Vega will prioritise work to redesign the home page in preparation for Go Live.
