### ISSUE TITLE
Roadmap improvements

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#195]
## Story

Improve the glanceability / legibility of the roadmap content (naming, bullets, different interaction / highlights / layout / less muted copy) + add CTAs for trading (testnet) and governance to current status

## Tasks

- [X] Briefing with designer
- [X] Explore and decide whether to use the launch takeover vegaverse concept for the roadmap and establish art direction
- [X] Detailed visual and interaction design (including addressing issues in description)
- [X] Team review
- [X] Responsive versions
- [X] Full set of visual assets (all planets created etc.)
- [x] Implementation
- [ ] Team Testing
- [X] Share with Vega
- [ ] Release

![Image](https://user-images.githubusercontent.com/47143694/190851799-5604ff20-7c4f-4f24-9688-6afa20ad0a56.png)

![Image](https://user-images.githubusercontent.com/47143694/190851804-a32f6003-736c-4bd3-9965-63f653037491.png)

**Comment by pennyandrews** [comment]
Here's the five points on the Roadmap. The last two (future) are purposefully muted in terms of their look as these planets are forming. When each launches we should update this graphic to reflect the new launch and the fully formed planet will be revealed.

Have placed in all content we have but there are some gaps 🙂

![Image](https://user-images.githubusercontent.com/47143694/190851822-d8147a04-dd9a-45a1-a82d-c83f8a4c50ae.jpg)
![Image](https://user-images.githubusercontent.com/47143694/190851818-fb774095-badb-4fab-9159-e9eeabc70672.jpg)
![Image](https://user-images.githubusercontent.com/47143694/190851820-7e32140b-5c09-4184-aa75-c978faf21866.jpg)
![Image](https://user-images.githubusercontent.com/47143694/190851819-f0fa2055-232f-450e-9470-e6f7ae46d195.jpg)
![Image](https://user-images.githubusercontent.com/47143694/190851821-68b8e3e1-76b7-446e-b8f5-1ea561eec642.jpg)

**Comment by goslingo** [comment]
@ckpringle just a note that this is ready for review, but we have some content gaps...

https://deploy-preview-298--vega.netlify.app/

**Comment by ckpringle** [comment]
Words - a few tweaks to the existing words too https://miro.com/app/board/o9J_lnkofoQ=/?moveToWidget=3458764537517099587&cot=14

**Comment by ckpringle** [comment]
Couple of things to look at 
* There's no mouseover / affordance to show you that the roadmap is interactive. Could we change the cursor to an arrow to show it? Fade in what you mouseover? Something else? 
* The text underneath (the bullets) are too disconnected from the step in the roadmap, not sure how obvious it is that the words change when you move position in the roadmap. Could we have the box transition with the content (but maybe in a way that means we don't have to show everything all at once... fade it out?)
* Small copy changes from feedback (sorry! See Miro https://miro.com/app/board/o9J_lnkofoQ=/?moveToWidget=3458764537517099587&cot=14)

**Comment by goslingo** [comment]
@ckpringle  new updates available: https://deploy-preview-298--vega.netlify.app/

- Cursor now changes to a pointer on hover
- Planets have a slight zoom effect on hover
- The text underneath fades in/out as it changes

**Comment by goslingo** [comment]
@ckpringle I've removed these words, so should be good to go 👍
