### ISSUE TITLE
🥽 Vega Validators page

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#196]
## Story
As a potential validator 
I want to understand the role of a validator on Vega, how that is different to other projects and how the rewards work 
So that I can make a decision to validate on Vega

## Acceptance Criteria 

- [ ] There is a landing page on .xyz under "Use Vega": "Validate and secure the network" 
- [ ] I can see it in the main nav and footer
- [ ] We've used the network parameter component to pull in the relevant network parameters 

## Tasks

- [ ] Design 
- [ ] Review (based on any new info we have from our work on the related docs)
- [ ] Implementation
- [ ] Testing

![Image](https://user-images.githubusercontent.com/46783148/191474231-e16c6ada-fde1-4ad0-bbd7-fc951fbb14f2.jpg)

Link to Sketch on Miro https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764532039890120&cot=14

**Comment by joellecharlotte** [comment]
Figured it was worth attaching where I got to with the Validators page. Needs work on the content part esp. below the table. Started exploring callout vs centre aligned text. Definitely could do with some colour / illustration / pizzazz 😬 - any imagery there is _very_ placeholder 

Haven't look at XS breakpoint yet and how the table would work either.

![Image](https://user-images.githubusercontent.com/113684458/191942638-59ebe22c-d2e3-4145-aa10-63ec7dae9011.png)

**Comment by joellecharlotte** [comment]
Revised design based on a review with @ckpringle. Tried to inject a little "pizzazz" with an illustration at the bottom that represented the three validator roles, with the colours corresponding with the **_Validator Score_** arrow above. 

@goslingo are there any issues with the proposed design where the arrow might span some columns in the table? (I also need to address how this table works on mobile)

@bigfandavid do you have any violent reactions to the illustration I put together at the bottom? 😬 

![Image](https://user-images.githubusercontent.com/113684458/192304700-e8ed31be-893f-4532-ae2f-678d0692b138.png)

**Comment by goslingo** [comment]
Looking great @joellecharlotte! I'm sure we'll be able to get that arrow to work 👍🏻

**Comment by bigfandavid** [comment]
The only little thing is the Vegabonds tend to sit on the baseline. I think that would work here... I also feel they could come up in size against the other things (sorry, I don't know what they are!) :)

**Comment by joellecharlotte** [comment]
Sure thing @bigfandavid, I see that now about the baseline. Will make some adjustments and share with you 😊

**Comment by JonRay15** [comment]
is this on track to be delivered in the current sprint?

its in Asana as being due on the 6th October?  I am thinking of running the blog on this subject on the 17th Oct, so there will be a little wiggle room either way.  But we should make sure our wording is aligned in this area, and I'll be linking to your page (and obviously the docs) from the blog. 

Draft of the blog can be found here. https://docs.google.com/document/d/1_u4ZdD1kaZ9xjeFurS1HvpELn3voXkIP-oUAJ_31W7Q/edit?mode=html#

Thanks

**Comment by ckpringle** [comment]
Build preview https://deploy-preview-230--vega.netlify.app/validators

**Comment by rebeccajsimmonds** [comment]
Joh Ray is hoping this page can go live on / or around Monday 16th Jan. It is waiting on Dev Ops to deploy the sandbox.
