### ISSUE TITLE
Vega latest... improvement

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#198]
## Story 

As a user
I want to see the latest and greatest content from / about Vega
So that I can stay up to date and understand what's happening right now

## Acceptance Criteria

- [ ] I can see the latest tweet
- [ ] I can see the latest blog post
- [ ] I can see the latest talk 
- [ ] I can see the latest content from third parties about Vega 
- [ ] I can see the key places that Vega are being featured / listed in the industry

## Tasks

- [X] Include making latest talks more prominent
- [X] Include twitter feed to 'latest news' section of the website
- [X] Sketch general direction
- [X] Design
- [X] Investigate how we can pull in a tweet with / without an image
- [X] Fix 'x minutes read' bug with medium feed https://github.com/vegaprotocol/vega.xyz/issues/180
- [X] Review mobile view
- [X] Share with Vega 
- [X] Implementation
- [x] Add `@vegaprotocol` as a title for tweets
- [x] Add external link style to titles for tweet, blog, and insight items
- [ ] Team Testing
- [ ] Release 

## Sketch

<img width="1000" alt="Screenshot 2022-09-05 at 17 31 00" src="https://user-images.githubusercontent.com/47143694/190854231-9ccda0b7-48b3-4705-b974-01c4f3ffa480.png">

## Example Content

Partners and backers research papers we might include in the 'what others say' category https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1655469056168709
https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1655469181576189

**Comment by pennyandrews** [comment]
Joëlle:

Here is the [Slack thread](https://vegaprotocol.slack.com/archives/C03HG3YNNNM/p1662480208064509) → 
Here is the [Figma page](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=569%3A21766) →

In summary:

Options with / without border for the cards
Option to include a tag
Do we want to distinguish cards for Latest News vs As Seen On
Some questions around when to use centred vs left aligned heading and what is and H1, H2 etc. A bigger question but perhaps for this task it would be useful to identify Primary vs Secondary headings

**Comment by pennyandrews** [comment]
Joëlle:

XL 1280 breakpoint updated following a review with Calum and Oli. Let me know if you need clarity on anything or need assets exporting [@Oliver Gosling](https://app.asana.com/0/1201845882267642/list). I'm working on the XSM 375 breakpoint. 

Design

[XL 1280 Figma frame](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=669%3A32582) → 

Cards for Latest News and As Seen On 

No border
Have the option to include a tag, this sits under the content
Both use the same card component in the Design System but with a bunch of layers turned off for As Seen On. Font sizes & colours are the same as the Key Features "cards".

Footer CTAs

1 - Use the network https://vega.xyz/use
2 - Join the community https://vega.xyz/community
3 - Govern the network https://vega.xyz/governance
4 - Develop on Vega https://vega.xyz/develop

XL 1280.jpg

**Comment by pennyandrews** [comment]
Joëlle:

**Homepage with Latest News**

I think the max width for Latest News / As Seen On cards works - there isn't much within the breakpoint anyway before the viewport is such that the cards fill the width. I think this solution is a bit nicer than going full width with huge cards and wide text boxes and follows the pattern of the three "cards" at the top (CONSOLE / GOVERNANCE / BLOCK EXPLORER) 

Only comment would be the alignment of button before - "VIEW DETAILED ROADMAP" - feels a bit misaligned, perhaps a next iteration could be centring this button like we do on the higher breakpoints but will defer to [@David R](https://app.asana.com/0/1201845882167123/list) on this. Overall I think this approach is good and maybe just needs some minor tweaks to padding before / after but think this should be handled as a separate task which would be part of the review of all headings and spacing tokens across all breakpoints.

Another small thing I noticed is there are two "join the community" CTAs at the bottom of the page - one should be "govern the network".

**Comment by pennyandrews** [comment]
@goslingo I've been doing a bit of testing and notice that the latest Tweet isn't being pulled in so this needs to be investigated...

![Image](https://user-images.githubusercontent.com/47143694/190854427-a8cf1484-8ba5-4668-8b4a-f37b9a92d9a5.png)

**Comment by pennyandrews** [comment]
A less important thing I wanted to poke at is whether we need to do something to show that the blog, tweet and insight cards link to external places (in a new window). We have the arrow pattern for normal links but not sure if we have an existing way of showing it for a card @ckpringle @neildawson @joellecharlotte @bigfandavid ?

**Comment by ckpringle** [comment]
On light mode, the tags are missing a (light grey?) background

![Image](https://user-images.githubusercontent.com/46783148/191050365-19656921-34a4-468c-becb-c66a905441e0.png)

**Comment by neildawson** [comment]
Yeah ideally we would indicate they're external @pennyandrews, and yes it would be best if we stuck to the same design cue we use elsewhere. I don't know if there's an existing pattern for cards, so I've made a crude mock-up below of the normal external link style on these cards. The natural place for the arrow is the title, but tweets don't have a title, so an alternative is the medium tag (e.g. "TWEET").

<img width="531" alt="image" src="https://user-images.githubusercontent.com/1080322/195041706-64fa52c0-e546-474b-9416-6009a04d5f1f.png">

**Comment by neildawson** [comment]
Picking up conversation in [this Slack thread](https://vegaprotocol.slack.com/archives/C0473D9HN05/p1666705446462189)

**Comment by neildawson** [comment]
[We reached a decision to add the name of the twitter account as a title for tweets](https://vegaprotocol.slack.com/archives/C0473D9HN05/p1666859025721439?thread_ts=1666705446.462189&cid=C0473D9HN05), so we can add the external link style to all titles in the section.

**Comment by goslingo** [comment]
Hey @neildawson this is ready for review...

https://deploy-preview-309--vega.netlify.app/
