### ISSUE TITLE
🧑‍⚖️ Implement In context linking between market creation and governance pages

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#211]
## The Chore

We need improve the in context interlinking between the governance and market creation pages. 

We have a module already on the develop page that gives us a pattern we could potentially reuse (attached), and a sketch from Cal on a callout from the market creation page to the governance page (attached) and visuals representing governance and market creation that we can utilise to build recognition when moving between the two pages.

On the market creation page this would replace the existing call out to governance on this page (attached)

## Tasks

- [X] Review existing pages, sketches and visuals
- [X] Design governance callout 
- [X] Design market creation callout
- [X] David review designs
- [x] Implement governance callout on market creation page
- [x] Implement market creation callout on governance page
- [x] Remove market creation module from the develop page
- [ ] Team Testing
- [ ] Release

## Component design 
[Market Creation Cross Link](https://www.figma.com/file/QF2XBeAscQf9ebzbzBE4V7/Governance?node-id=673%3A34002) (XL)
[Market Creation Cross Link](https://www.figma.com/file/QF2XBeAscQf9ebzbzBE4V7/Governance?node-id=673%3A33730) (XS)
[Governance on Vega Cross Link](https://www.figma.com/file/QF2XBeAscQf9ebzbzBE4V7/Governance?node-id=673%3A34788) (XL)

**Comment by pennyandrews** [comment]
Joëlle:

Please see [this link](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=62%3A5641) → 

These show a proposed design for the callouts, using an image for these but the idea is that a callout component could have an image or not and be used elsewhere across the site (eg. on the Community page)

I was wondering if we could use rounded corners and introduce a background tint to help distinguish these callouts from the rest of the content and make it feel like the entire thing was clickable.

Desktop Screens
Market Creation XL
Governance on Vega XL
- Sidenote: this is using the new "Tools Card" component which is used in the "Use the Network" page too.

Mobile Screen
Market Creation XS

Let me know your thoughts!

**Comment by pennyandrews** [comment]
Hey Joëlle - thanks for this, looking good.

We do have an off-black that we use on the Develop page within the Live Bounties section so I definitely think we can use this again. May be worth matching the colours.

The round corners definitely distinguish this from other elements. Can I check the radius of these? My design OCD would like them to be the same as the Tools icons which is 12px - it may be the same already, just checking 🙂

<img width="488" alt="Screenshot 2022-07-26 at 13 50 59" src="https://user-images.githubusercontent.com/47143694/191117379-ebb9c360-446f-486c-80fd-15c3976f8a04.png">

**Comment by pennyandrews** [comment]
Joëlle:

Good shout to use the same off-black, have updated. Corner radius is indeed 12px 😁

Questioning now the use of a border, not sure it's needed or maybe it is... attached options of both border and no border for the image and no image callouts.

![Callouts](https://user-images.githubusercontent.com/47143694/191117573-9ece63dc-47e5-4c03-b3e7-adbf982c4b2a.png)

**Comment by pennyandrews** [comment]
David:

I think with for these [@Joëlle Snaith](https://app.asana.com/0/1202216849708246/list) - not everyone has lovely screens like us and without may be too subtle for a call-out?

**Comment by pennyandrews** [comment]
Joëlle:

Sold [@David R](https://app.asana.com/0/1201845882167123/list)! With border it is 💃

**Comment by pennyandrews** [comment]
Joëlle:

Here are the templates with the final callouts. LMK if any last tweaks.

[Market Creation Cross Link](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=62%3A5641) (XL)
[Market Creation Cross Link](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=72%3A10703) (XS)

[Governance on Vega Cross Link](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=74%3A5899) (XL) 
What copy should go in this callout?

I'll create components of these callouts (with / without image + breakpoints when done with Community Pages)

**Comment by pennyandrews** [comment]
Calum:

[@Joëlle Snaith](https://app.asana.com/0/1202216849708246/list) I think "Propose a futures market on any underlying." would do the job with link "Create a new market". Have updated in the Figma. Position wise I'd place it underneath the tools. (By the way, the tool icons are slightly out of date, but doubt that matters!)

**Comment by pennyandrews** [comment]
need to update Figma links to whereever these designs are now in the design system @joellecharlotte

**Comment by joellecharlotte** [comment]
Links are updated above!

**Comment by goslingo** [comment]
@ckpringle ready for review

https://deploy-preview-316--vega.netlify.app/governance/
https://deploy-preview-316--vega.netlify.app/market-creation/

**Comment by goslingo** [comment]
@ckpringle the position of the callouts have been moved to below the accordions 👍

https://deploy-preview-316--vega.netlify.app/governance/
https://deploy-preview-316--vega.netlify.app/market-creation/
