### ISSUE TITLE
👯Tie in develop section with new builders club content / page (develop landing page tweaks)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#213]
## The Chore

I want to immediately understand how I can get help building on top of Vega and the bounties available
So that we might increase interest in the builders club

## Tasks

- [ ] Update builders club call out copy and positioning, with an Apply button linking to https://vegaprotocol.typeform.com/to/YgOgiGqF and link "See what's going on" to the new builders club page
- [ ] Show only the latest bounties in the table, limited to 3 with a CTA to "Developer bounties" here https://github.com/vegaprotocol/bounties/
- [ ] There are CTAs to continue the journey from this page to say hello on discord, join the builders club, explore the docs?
- [ ] We've removed the API module 
- [x] Update design for Develop/Getting Started page
- [x] Updates to Ambassadors page

## Additional details / background info

Miro sketches https://miro.com/app/board/o9J_lnkofoQ=/?moveToWidget=3458764532784741218&cot=14

**Comment by ckpringle** [comment]
@bigfandavid what's the latest on this ticket?

**Comment by bigfandavid** [comment]
@ckpringle - When I originally looked at this I went a little further design-wise than was expected. However I, for one, would love to see the changes implemented, as I think it's a vast improvement.

You can see the Builders Club page and updated Develop and Ambassador/Commuity pages alongside each other here: https://www.figma.com/file/wA0tK5ZE0Rr0qac6RO0buF/Builders-Club?node-id=1181%3A33039

(Ignore the weird logos on some of these designs, I've ask Joelle if there's a quick fix)

**Comment by ckpringle** [comment]
@joellecharlotte to pick up on componetising this work for consistency with the design system -

**Comment by joellecharlotte** [comment]
@goslingo

Here are the revised designs in Figma: [Link ↳](https://www.figma.com/file/AlPkMuAwHtfSQCeaZRrpkv/Develop?node-id=1860%3A5018)

This includes the Leaderboard Detail page with updated components.

The components can be found in the [Tiles page](https://www.figma.com/file/lUnbFEwfGdxKOThTgmewam/Block-Components?node-id=1%3A13) and the [Leaderboard List page](https://www.figma.com/file/lUnbFEwfGdxKOThTgmewam/Block-Components?node-id=125%3A4592)

Join the Community buttons can be found in the [Buttons page](https://www.figma.com/file/xQ3VaojxgeNMb9wvjr9D0B/Nested-Components?node-id=1%3A7)

_Note: the numbers in the Leaderboard List Items are detached from any typestyle as they use stylistic alternatives which are not part of the heading or body styles._

**Comment by goslingo** [comment]
@ckpringle @pennyandrews ready for review...

https://deploy-preview-344--vega.netlify.app/develop/
https://deploy-preview-344--vega.netlify.app/community/ambassadors/
https://deploy-preview-344--vega.netlify.app/builders-club/
