### ISSUE TITLE
Showcase contributors

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#217]
## Story

As a user
I want to understand who is contributing to the Vega project and to what extent people are contributing
So that I can assess how active the project is and the quality of it's contributors

## Acceptance Criteria

- [ ] I can see more useful information when I hover over a contributors profile pic*
- [ ] I can filter / sort the list of contributors in some useful way**
- [ ] I can see a graphical view of contributions***
- [ ] I can link to a filtered view of contributors (by project / repo or something) from the "made by" tags on the use vega page

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

**More useful information on hover ***

_Summarised notes from Barney on Slack_

The "81 contributions" text on the contributors page is misleading as it counts such a small subset of the work people have done. We could improve the hover to give a better sense of the contributor and their role:

- develop a simple algorithm to look at the length of time someone spent as a contributor as well as number of commits etc. and give them a rank/category like gold/silver/bronze or some other wackier names
- annotate with a badge for project team members (i.e. actual repository members)
- perhaps have little tags for which (if any) of the major repositories/projects/components (core wallet, data node, Console, specs, etc.) they have contributed to

<img width="629" alt="Screenshot 2022-07-19 at 16 44 35" src="https://user-images.githubusercontent.com/47143694/191126186-87b4e9a4-6b90-4053-a725-2fc06706344a.png">

**Filter / sort contributors ****

Speak to Chris about this

Load more... something that allows us to pre-empt scale and give the impression there are even more than you can see on the page?

Filtering / sorting:
- Random (default)
- By number of contributions
- Most recent contribution
- Vega team only?
- By Repository?
- Anything else?

**Graphical view of contributors *****

Speak to Chris about how we can pull this in from github

![Image](https://user-images.githubusercontent.com/47143694/191130956-82c213bc-1206-4be8-a772-17b80b104c30.png)
