### ISSUE TITLE
Review pages for design quality / consistency and visual hierarchy

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#218]
## The Chore

What we need to achieve and who for

## Tasks

- [ ] Consistency of page headers / hero areas i.e. HUGE image at the top of community page 
- [ ] Include our use of grey text across the site as often missed or misinterpreted as greyed out 
- [ ] Readability of green text against light theme (see attachment)
- [ ] Can we do something about the nav items being far away from the thing you click on e.g. centre align for learn? Left align?
- [ ] Make filter navigation more mobile friendly and scalable to more tags in the future on use vega page

## Additional details / background info

i.e. Link text design - greyed out?

There's been a couple of comments on things looking too muted, Candida just mentioned about the text links in the market creation steps but obviously that pattern has been applied elsewhere - and I agree the grey-ing out kind of makes it feel like you shouldn't read it? 

<img width="1440" alt="Screenshot 2022-07-20 at 16 31 22 (1)" src="https://user-images.githubusercontent.com/47143694/191127162-c402b97e-1fd0-453a-a1be-1c52afca4607.png">
