### ISSUE TITLE
Bug Bounty improvements

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#220]
## The Chore

What we need to achieve and who for

## Tasks

- [ ] Design the page e.g. page header and content layout, input field v call out
- [ ] Improve the copy e.g. make it clear that if you submit anonymously then we can't reward you
- [ ] Link to from Community page and sub nav (contribute)
vLink to from Develop page and sub nav (contribute)
