### ISSUE TITLE
IPFS process / requirements for governance

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#222]
## The Chore

What we need to achieve and who for

## Tasks

- [ ] Work out the process around adding an IPFS link - i.e. what file format, do we need a file template, how to upload, anything else
- [ ] Create content required to help people create an IPFS link inc. existing forum post template content
- [ ] Update .xyz, forum (testnet and mainnet) and doc site process descriptions

## Additional details / background info

From Barney 

Probably what'll happen is the proposer adds the MD from the forum post detailing the change and the reason to IPFS before submitting the proposal and includes the IPFS URL in the proposal. We would, though, expect:
the process docs to include info about this; and
the front end to pull in (and perhaps process as markdown) the content at the URL, and also to flag if it is a non-immutable URL and probably disable the button to vote for it in that case.

**Comment by pennyandrews** [comment]
See slack thread about this ticket https://vegaprotocol.slack.com/archives/C03UTQ34MMY/p1674229382051869
