### ISSUE TITLE
One pager website for Gobalsky Labs Limited

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#223]
## The Chore

For regulatory purposes and making it clear Vega is not Gobalsky Labs Limited, Vega is the software platform

## Tasks

- [x] Design logo and colour palette 
- [x] Tech set up (where is this going to be hosted etc.?)
- [x] Build the site designing in browser
- [ ] Review build with team
- [ ] Test build
- [ ] PR
- [ ] Deploy

## Additional details / background info

Dependent on creation of the brand https://github.com/vegaprotocol/ux-and-visual-design/issues/15 and content

**Comment by bigfandavid** [comment]
Link to Figma here: https://www.figma.com/file/onPH7ZYQooADU76zjmVV4i/Gobalsky-Landing-page?node-id=669%3A32582&t=so96V98vg6HX8IqG-1
