### ISSUE TITLE
On / active state in primary navigation

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#225]
## Story

As a user
I want to know where I am in the site in relation to the navigation menu
So that I can orient myself when navigating through the content

We may want to consider the URL structure as part of this? 

## Acceptance Criteria

- [ ] I can visibly see which section of the website I'm in from the primary navigation when not interacting with it
- [ ] I can still see which section of the website I'm in in the sticky nav when I scroll down the page 
- [ ] I can

## Tasks

- [ ] Explore and come up with solutions to how to implement this when we have pages appearing in multiple sections of the site
- [ ] Team and stakeholder review
- [ ] Visual Design (designs already done - see below - but might need to be updated depending on the solution agreed)
- [ ] Team review
- [ ] Implement
- [ ] Team Testing
- [ ] Share in Slack
- [ ] Release

## Design

![image](https://user-images.githubusercontent.com/47143694/191317991-fc47a02c-79b0-40f7-8353-23aa2a03437e.png)
