### ISSUE TITLE
Markets Challenge

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#228]
## The Challenge

![image (20)](https://user-images.githubusercontent.com/47143694/191862949-3577dad7-44e8-4647-a336-15142d10451d.png)

## Tasks

- [ ] Gather information about existing markets and an understanding of regulatory constraints to listing them on the website 
- [ ] Map out the journey's to find market information (including impacts on existing website structure and content and that of other Vega apps and channels)
- [ ] Sketch out requirements
- [ ] Write tickets on the relevant backlogs and coordinate implementation across teams / functions 

## Additional details / background info

<img width="1918" alt="Screenshot 2022-06-06 at 16 36 29" src="https://user-images.githubusercontent.com/47143694/191863378-a5b89965-3dc3-4749-a283-c5eb38bb78e3.png">
<img width="1919" alt="Screenshot 2022-06-07 at 11 26 35" src="https://user-images.githubusercontent.com/47143694/191863382-c420bf47-af56-45cf-980c-3053c12551bc.png">

Could we have 'number of active markets' data displayed in the ticket (along with some other trading data?) and have that link out to the market list on console?

**Comment by pennyandrews** [comment]
Created in wrong repo
