### ISSUE TITLE
Reflect the new "new proposal" journey on token on website + forum

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#235]
## Chore

Now that you can create a proposal in the UI of token front end, we need to update the content on the website to reflect this. Assumption that this involves copy changes only.

## Acceptance Criteria

- [ ] I can see that I can create and submit a proposal on the token front end from the website governance page and market creation page and forum guide topic(s)

## Tasks

- [x] Read through what we have right now on the governance page, market creation page and forum guide topics and identify where updates to share this new feature
- [ ] Update [testnet forum post](https://community.vega.xyz/t/about-fairground-testnet-governance-proposals/4016), changing:
  > Vote and submit a proposal on chain using the [Vega Token dapp](https://token.fairground.wtf/)

  to

  > Use the Vega Token dApp to [vote on proposals](https://token.fairground.wtf/governance) and [submit your own](https://token.fairground.wtf/governance/propose/)
- [ ] Update the [mainnet forum post](https://community.vega.xyz/t/about-the-governance-category/3849), changing:
  > Vote and submit a proposal on chain using the [Vega Token dapp](https://token.vega.xyz/governance)
  
  to

  > Use the Vega Token dApp to [vote on proposals](https://token.vega.xyz/governance) and [submit your own](https://token.vega.xyz/governance/propose)
- [ ] Make updates!

## Additional details / background info
"New proposal" feature here - https://token.vega.xyz/governance/propose

**Comment by neildawson** [comment]
@ckpringle can I have a sense check here, proposed changes: https://github.com/vegaprotocol/vega.xyz/pull/263/files

Is that all there is to it? I know I will need to edit the translation files too. if this is right, and I'll need you to edit your forum posts.
