### ISSUE TITLE
Staking rewards total and average APY

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#238]
## Chore 

For staking, on the new rewards landing page, we want to show the total staking rewards paid out and average APY for an LP to demonstrate how lucrative it is. 

## Acceptance Criteria 

- [x] I can see an average APY for staking rewards on the rewards page on vega.xyz for the last epoch to three decimal places
- [x] I can see a total of staking rewards paid out for the last epoch rounded to the nearest whole $VEGA
- [x] I can find an explanation of how it is calculated 

## Sketch

`Last epoch`
`Treasury Rewards         10,000 $VEGA       16.6% APY`

## Tasks 

- [x] Set up a new Vega key supplied with $14 VEGA 
- [x] Stake 1 VEGA to each consensus validator from that wallet
- [x] Build a query for the total rewards paid out (the ACCOUNT_TYPE_GLOBAL_REWARD)
- [x] Build average APY

## Calculation

We set up a new Vega key owned by the website team and we supply it with 14 $VEGA.
We stake 1 VEGA to each of the 11 current validators (soon to be 13 again, and then after launch 14, hence the 14 VEGA in the wallet...we could put more in the wallet to save ourselves transferring more later).

Then all we need to do is query the rewards API for the party ID of our Vega key.

https://api.vega.xyz/parties/603f97f4499634372cc0fe50f4a0834bdf662d0b54c15b0bac5832367bae239b/rewards

(will substitute proper key shortly)

You will get output that looks like this
```
{
      "assetId": "d1984e3d365faa05bcafbe41f50f90e3663ee7c0da22bb1e24b164e9532691b2",
      "partyId": "d5a907eae0544c70c00ffe3d91320a00ee823db9b2d375111135378a56905892",
      "epoch": "388",
      "amount": "169250786139011275",
      "percentageOfTotal": "0.0027685138769",
      "receivedAt": "1670175329646999000",
      "marketId": "!",
      "rewardType": "ACCOUNT_TYPE_GLOBAL_REWARD"
    },
```

Therefore you can find the total rewards given out in that epoch by doing 

`(amount / 10^18) / (percentageOfTotal / 100) = Total rewards that epoch`

In the example above you should therefore get 

`0.169250786139011275 / 0.000027685138769 =  6113.416572`

Then:

`Average APY = Total rewards that epoch / Total staked on the network x 365 x 100`

So 

`Average APY = 6113.416572 / 29111863 x 365 x 100 = 7.664906395%`

## Explanation

( i ) The average annualised percentage return based on last epochs total rewards for staking / amount staked and the number of epochs [24hr] in a year.

**Comment by ckpringle** [comment]
Slack thread here - https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1669223848869389

**Comment by goslingo** [comment]
Calculated APY can be seen here:
https://deploy-preview-185--vega.netlify.app/rewards/

**Comment by goslingo** [comment]
The following two acceptance criteria still needs considering...

- I can see a total of staking rewards paid out for the last epoch rounded to the nearest whole $VEGA
- I can find an explanation of how it is calculated

Do we still want these? Should they be split out into a different ticket?

**Comment by JonRay15** [comment]
these are done now right?

**Comment by goslingo** [comment]
> these are done now right?

If everyone is happy with the wording, layout, and the calculations are checking out, then it's good to go! 😎
