### ISSUE TITLE
Update content and links for Alpha Mainnet Release

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#241]
## Story

As a visitor
Now that Alpha Mainnet is live (and therefore now the _**primary**_ network)
I want to be linked to mainnet for all key information and actions
So that I can understand the state of the project and actively participate

## Tasks

- Rewards
  - [ ] Update CTA '[Create your own reward](https://docs.vega.xyz/testnet/concepts/trading-on-vega/fees-rewards#setting-rewards)' to link to mainnet docs https://docs.vega.xyz/mainnet/concepts/trading-on-vega/fees-rewards
  - [ ] Update PROVIDE LIQUIDITY CTA to link to https://docs.vega.xyz/mainnet/concepts/liquidity/provision
- Governance 
  - [ ] Update [Read the docs to make a proposal](https://docs.vega.xyz/mainnet/concepts/vega-protocol#governance) to [Read the docs to make a proposal](https://docs.vega.xyz/mainnet/tutorials/proposals)

**Comment by pennyandrews** [comment]
Neil to review and add anything to the tasks based on anything that has been added or significantly changed since we did the original spike.

**Comment by neildawson** [comment]
@pennyandrews @goslingo I did a sweep of the site and updated the task list

**Comment by rebeccajsimmonds** [comment]
Are we still OK to use 'Trade' in the footer?
