### ISSUE TITLE
Animate hero images on important pages

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#242]
## Story

As a member of the Vega team
I want the website to feel lively and quirky
So that visitors have a memorable experience

## Acceptance Criteria

- [ ] The following key website pages have animated flourishes:
  - [ ] Governance
  - [ ] Join the community
  - [ ] Key concepts
  - [ ] Develop
  - [ ] Market creation

## Tasks

- [ ] Explore and storyboard animations for animating the hero image on each page
- [ ] Check development feasibility
- [ ] Team review
- [ ] Prioritise the list so we can work in order
- [ ] Visual Design
- [ ] Implementation

## Additional details / background info
- This and https://github.com/vegaprotocol/vega.xyz/issues/243 should be considered together and timeboxed, with priority given to https://github.com/vegaprotocol/vega.xyz/issues/242
