### ISSUE TITLE
Create animations for key concepts

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#243]
## Story

As a member of the Vega team
I want the key concepts area to feel lively and quirky
So that visitors have a memorable experience

## Acceptance Criteria

- [ ] Most illustrations on the Key Concepts page have animated flourishes

## Tasks

- [ ] Explore and storyboard reusable animations for common elements seen across the page (see details below)
- [ ] Check development feasibility
- [ ] Team review
- [ ] Prioritise the list so we can work in order
- [ ] Visual Design
- [ ] Implementation

## Additional details / background info
- As there are lots of illustrations on this page, the idea here is to animate some small elements that are seen in multiple places, so a smaller number of simple animations can bring life to the whole page. For example:
  - Using the glitchy rainbow video background, like on the homepage
  - Animating the pixellated "sparkles" to start small, expand, and pop out of existence on a loop
  - Blinking, winking, or waving characters
  - Waving flags
  - Spinning coins
  - Vibrating cars and boats
- This and https://github.com/vegaprotocol/vega.xyz/issues/242 should be timeboxed, with priority given to https://github.com/vegaprotocol/vega.xyz/issues/242
