### ISSUE TITLE
Trade futures

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#253]
## Chore 

As a team we want to make it clearer that you can trade futures on Vega (rather than perps, options - yet!) so that potential users know exactly what they can do right now. 

## Tasks 

- [x] Update the description of Console on the landing page AND on the use vega page to "Trade cash settled futures on the fully decentralised Vega network"
- [x] Reflect "Alpha mainnet is live with cash settled futures" in trading takeover / equivalent (speaking to Mary, David and Oli)
- [x] Create markets page
  - [x] update intro para to "Create a futures market"
  - [x] mention the fact Vega's alpha mainnet currently supports cash settled futures
- [x] Update trading CTA on website top right to "Trade futures (Testnet)" 
- [x] Update roadmap description of V1 Mainnet to include spots and perpetuals 
- [x] Update roadmap description to add that this could include advanced products like options (community generally interested in them)

**Comment by neildawson** [comment]
[Pull request](https://github.com/vegaprotocol/vega.xyz/pull/299)
[Deploy preview](https://deploy-preview-299--vega.netlify.app/)

- Adding “futures” to the nav CTA breaks the layout at some viewport widths. This may be exacerbated in languages other than English. Should we:
  - Remove “(testnet)“?
  - Wait until trading launches so we can say “Trade futures” without “(testnet)“?
- We have a Spanish translation for that CTA. Now we’re changing it, how do we flag that it needs translated again? Do we just overwrite the Spanish translation with English for now?
- Spot markets were already mentioned, I've added mentions of perpetuals and options, need someone to check what I've written makes sense
- Creating a new component to add more info here seems like overkill, needs some thought to see if we can integrate this in plain text

**Comment by neildawson** [comment]
- Mary has added cash settled futures to [the trading takeover script](https://docs.google.com/document/d/1MIu8wHmawQbndbOhmMPscFm4oJ8w3amD9Tixz71zdKU/edit), so that go live along with that feature
- Calum has updated [the copy for the new roadmap](https://miro.com/app/board/o9J_lnkofoQ=/?moveToWidget=3458764537517099587&cot=14), too, so this will also be reflected when the new version goes live
- Calum confirmed my suggestion for the other copy changes
