### ISSUE TITLE
Offer trading stats on the homepage

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#255]
## Story

As a website visitor interested in trading
I want to determine the health of trading on the Vega network
So I can decide if it's worth participating

## Acceptance Criteria

- [ ] I can find meaningful statistics which summarise activity on the Vega network

## Tasks

- [ ] Sorting exercise to settle on a new list of figures for the homepage stats section, working with:
  - The stats already implemented:
    - Number of validators 
    - Total amount staked
    - Average block time
    - Current epoch
  - Possible trading stats suggested by Barney:
    - Daily traded volume
    - Dollar value in the Vega bridge
    - Dollar value that has been traded
    - Number of trades
    - Number of public keys
    - Rewards paid out
    - Fees paid
- [ ] Sense check with Dave to ensure we are comfortable publicising these stats
- [ ] Determine who will build an API to deliver these stats
- [ ] Determine if we need a service to convert different assets into dollars for summary purposes

## Additional details / background info

i.e. token prices, trades / transactions / no. markets. no. notes / validators, performance etc.
