### ISSUE TITLE
Offer task-oriented journeys

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#256]
## Story

As a website visitor interested in only one or two items from: trading, staking, governance, market creation, validating…
I want a clear indication of which resources relate to my use case
So that I can ignore irrelevant content

## Acceptance Criteria

- [ ] I can browse content both by tool/application and by use case:
  - [ ] Governance
  - [ ] Trading 
  - [ ] Staking
  - [ ] Market creation
  - [ ] Validating/node operation

## Tasks

- [x] Agree list of use cases
- [x] Identify key entry points and touchpoints (e.g. main nav, use the network page, anywhere else appropriate)
- [x] Sketch journeys for each
- [ ] Implement new tab structure in PR
- [ ] Review with stakeholders
- [ ] Merge

## Sketch
- [Miro exploration](https://miro.com/app/board/o9J_lnkofoQ=/?moveToWidget=3458764538788714087&cot=14)

**Comment by neildawson** [comment]
New tab structure for the apps on the Use Vega page. Note the repetition of Staking and Desktop Wallet.

![Image](https://user-images.githubusercontent.com/1080322/204513041-dd40af25-329f-431a-bdef-3827f275e665.png)

In addition, we want to add a message to the governance tab, pointing people to the Governance page. I believe this is an existing component:

![Image](https://user-images.githubusercontent.com/1080322/204513238-e556d875-209f-42be-99d7-fabff87d2ea4.png)

Copy:

> **Vega is governed by its token holders**
Token holders propose changes to the network, vote on proposals, create markets, and nominate validators by staking.
