### ISSUE TITLE
Update list of talks

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#257]
## The Chore

Nissa and Edo maintain a spreadsheet of past and planned talks. It's updated often, and the website is currently out of sync with it.

## Tasks

- [x] Nissa and Edo to collated content that needs to be added
- [x] Give Di, Nissa and Edo a walkthrough of how to update talks on the website using real examples
- [x] Update list of talks
