### ISSUE TITLE
Create a trading landing page

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#264]
## Story

As a visitor interested in trading
I want a destination which introduces trading on Vega and its USPs
So that I can compare it to competitors

## Acceptance Criteria

- [ ] I can find a breakdown of why trading on Vega is unique and preferable to other platforms

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info
- We have dedicated pages for governance and market creation. Trading is another of the key use cases, so it feels like this deserves the same treatment.
- Counterargument: We already have a clear CTA to trading in the nav., and work is underway on a first time use experience for console which may serve the same purpose better.

**Comment by pennyandrews** [comment]
This might be more valuable once there are more trading apps on Vega
