### ISSUE TITLE
Add partner logos and links

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#268]
## The Chore

The [Partners & Backers](https://vega.xyz/partners-backers) page is very dry. Add logos to increase visual interest.

## Tasks

- [ ] Source logos and for as many partners as possible
- [ ] Adjust design to cater for logos
- [ ] Stakeholder/team review

## Additional details / background info
- It's likely some partners won't have logos, or we can't find it in acceptable quality, so we'll need to have a decent placeholder or empty state
- May need help from Vega team to get good quality logos - who can help?
