### ISSUE TITLE
Create a visual to explain the validator journey

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#269]
## Story

As a potential validator
I want to understand the process of becoming a validator and earning rewards
So that I am informed enough to decide if it is right for me

## Acceptance Criteria

- [ ] I can see a visual representation of how validators move between the candidate, standby, and consensus states
- [ ] I can see a visual representation of how validators are rewarded at each stage

## Tasks

- [ ] Sketch concepts for diagram
- [ ] Team and stakeholder review
- [ ] Visual Design (including in situ on the validators page)
- [ ] Team review
- [ ] Implement on vega.xyz
- [ ] Implement on docs

## Additional details / background info
- Could tie in to https://github.com/vegaprotocol/documentation/issues/260 as we could also use this visual in the node operators section of documentation
