### ISSUE TITLE
Website vs Apps Design System

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#308]
## The Chore

What we need to achieve and who for

## Tasks

- [x] Create a plan with David
- [x] Set up a call with a key dev from each product team
- [x] Agree on an approach for systemising the Vega Design System across the Marketing Site & Apps
- [ ] Share tailwind config with the other apps

## Additional details / background info

**Useful links**

[Current Console v2 Toolkit in Storybook](https://vega-ui-toolkit.netlify.app/?path=/story/dialog--default)
[Blueprint icon set](https://blueprintjs.com/docs/#icons) (as a possible SVG icon set for functional icons)
[Tailwind CSS Library Figma Plugin](https://www.figma.com/community/plugin/785619431629077634)
[Current Tailwind Config](https://github.com/vegaprotocol/frontend-monorepo/tree/develop/libs/tailwindcss-config/src)
[Storybook & Figma](https://help.figma.com/hc/en-us/articles/360045003494-Storybook-and-Figma)
[Tailwind CSS](https://tailwindcss.com/docs/customizing-spacing)

**Comment by pennyandrews** [comment]
I believe the last task here is now covered by this separate ticket https://github.com/vegaprotocol/vega.xyz/issues/348 so I'm marking this one as done
