### ISSUE TITLE
Add 'current' point indicator to the roadmap

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#320]
## Story

As a user 
I want to know which of the points/planets on the roadmap Vega is at right now
So that I can be clear where we are at, what came before and what is coming up next

## Acceptance Criteria

- [X] The 'current' point on the roadmap is the first thing I see when I look at the roadmap (as it's where we are now)
- [x] I can see some kind of flag / label / content that tells me what is Vega's 'current status' / where we are now in our roadmap
- [x] The flag/label type thing that tells me which point on the roadmap we are on now, sticks with that item as I scroll through the other milestones/planets
- [ ] There is a way for non technical people to update the roadmap to change which point on the roadmap is the current status
- [ ] There is a way for non technical people to add new milestones (in multiple languages)
- [x] I can see the dates / timings written with the year first and Half/Quarter second to make it quicker to orient around timings (i.e. '2022 H1', rather than 'H1 2022')

## Tasks

- [ ] Explore / sketch the best way to indicate which is the current point in the roadmap
- [ ] Team (and stakeholder?) review
- [ ] Design
- [ ] Team review
- [x] Implement
- [ ] Team testing and PR review
- [ ] Release
