### ISSUE TITLE
Create default tailwind config that can be used across front end applications

### ISSUE THREAD

**Issue by goslingo** [vegaprotocol/vega.xyz#348]
## The Chore

Now that we have a design system established, we should create a single Tailwind config file that can be used across all front end apps.

This means we would be able to consistently apply the brand foundations such as colours, typography and spacing across all front end apps using consistent class names.

## Tasks

- [ ] Review the brand foundations and create tailwind config file
- [ ] Share with front end leads and refine
- [ ] Find out the best way to deploy this tailwind config across all apps
- [ ] Scope out what work might be required to update existing apps to work with it
