### ISSUE TITLE
Privacy Policy improvements

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#371]
## The Chore

To review and improve Vega.xyz privacy and cookie policy, considering Barney's feedback and the potential to surface our values and principles around privacy etc.

## Tasks

- [x] Mary to get up to speed with the background below
- [x] Mary to write a proposed alternative version of the privacy policy based on the background
- [ ] Rebecca / Penny to share, review, iterate and finalise with Barney and Dave Mac
- [ ] David to review and amend the page design (as needed)
- [ ] Oli to Implement
- [ ] Ben to test

## Background 

**Current privacy policy**
[live privacy policy on the website](https://vega.xyz/privacy/)
_Worth noting that this policy originated from the previous version of the website and was then reviewed, revised and approved by Edd and Dave Mac before putting live._

**Barney's points a while ago**
[slack thread](https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1651312695562499)

**Neil's proposal**
- Create a succinct, human readable summary of the privacy and cookies policy, which also expresses Vega's values and beliefs about privacy e.g. we believe in privacy and anonymity, it's important to us, so unless you sign up for something we don't capture or process your data. And if you do, we only do precisely what you've asked for.
- We don't use any cookies whatsoever. The only thing we store is your preference for light/dark mode, and language, and these use local storage in your browse, not cookies.
- We don't use any third party analytics service such as google analytics, we use only server logs, never tied to an individual.

**Comment by maryvaliakas** [comment]
This is the same essentially ticket as the other privacy policy ticket. Regardless, here is the doc!

https://docs.google.com/document/d/1lfIKJIgUeJqYIPkz9we1eUO3E2jiIm0al_Wnw_CmuG8/edit?usp=sharing

**Comment by pennyandrews** [comment]
Just waiting on getting access to the google doc then will share for feedback with the agreed stakeholders

**Comment by pennyandrews** [comment]
Dave is working on a revised version of the policy with Barney here https://docs.google.com/document/d/1qTuTCR9eQbgPuisErhHaTOcEELMmg-cgEUFqqa9mW3Q/edit
