### ISSUE TITLE
Migrate blog content

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#385]
## The Chore

Serotonin suggested it would be significantly beneficial for Vega to migrate all blog content into the website rather than Medium

## Tasks

- [ ] Understand whether this is the right thing to do
- [ ] Plan the work
- [ ] Implement the necessary changes on the website (considering content management etc.)
- [ ] Migrate content
- [ ] Etc.
