### ISSUE TITLE
Create redirect page for .xyz

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#390]
## The Chore

As a user
I want to know that I am leaving a Vega hosted site 
So that I know I should verify for myself that the destination is safe for me

Could create generically to be used anywhere 

Create a redirect page for .xyz, like https://hub.injective.network/external-link/

![Image](https://user-images.githubusercontent.com/46783148/205290150-0775e292-f22d-46bb-838e-4f3f9bc39b61.png)

## Sketch

The page takes some query params and uses them to redirect you.
 
- vega.xyz sends you to https://leaving.vega.xyz/#STRING
- The page tells you that you are being re-directed to STRING

so when linking to console the Vega.xyz might link to https://leaving.vega.xyz/#ipsf://console.vega.xyz
which re-directs you to ipsf://console.vega.xyz

It can either give you a button with a labeled declaration (if this is required) e.g. "I understand, go ->"
or just a button to go. and the option to copy a part of the URL (if you want/need to use another browser, or verify the hash
or it can have a countdown that auto-redirects after 5 seconds.

failing any further input I (@campbellssource) suggest the countdown option.

The page should show you the URL you are being redirected to.

please re-use existing design assets. e.g. the loading blocks, fonts etc.

Note: longer term we may have app specific redirect pages that give you hashes of builds etc. https://github.com/vegaprotocol/ux-and-visual-design/issues/81 

but this ticket is a generic solution that could be used for 3rd parties or before other solutions are developed

## Tasks

- [x] build something based on this
- [x] share for feedback
- [x] iterate
- [ ] verify which external links we want to utilise this for, just console?
- [ ] update
- [ ] test
- [ ] deploy

**Comment by pennyandrews** [comment]
I have created a thread in Slack to get a decision on this from Matt and Barney https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1673524730500779

**Comment by pennyandrews** [comment]
@goslingo decision on this is to put it live now, just for Console (links out to the Trading app) but covering testnet and mainnet - understanding that the mainnet one won't be used yet and you'll only see the one for the testnet link. This allows us to battle test it a little before Alpha Mainnet release. 

For testnet version we should review the wording to make sure it's still relevant. 

This[ slack thread ](https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1673524730500779) is a good place to pose any further questions / clarifications you need to be able to get this finished and live. Thanks
