### ISSUE TITLE
Add github to 'where we are'

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#394]
## The Chore

We would like to add a card to the 'where we are' section of the community page to include the vegaprotocol github org

## Tasks

- [ ] Create the icon with Vega colour background and github logo
- [ ] Check community and perception happy with the content
- [ ] Implement the new card 

## Additional details / background info

_Something like:_
Github
_URL to link to https://github.com/vegaprotocol_
Public repos for Vega Protocol and related apps and tools  

This is the page the card should be added to https://vega.xyz/community/
<img width="1556" alt="Screenshot 2022-12-05 at 09 26 01" src="https://user-images.githubusercontent.com/47143694/205637255-d46fdb19-b195-43dd-8cf6-e47322e4138e.png">

**Comment by maryvaliakas** [comment]
Text can say:

GITHUB

Explore our online repositories, or collaborate with the Vega teams.
