### ISSUE TITLE
Add Mainnet Sims to fairground.wtf with updated branding

### ISSUE THREAD

**Issue by goslingo** [vegaprotocol/vega.xyz#404]
## Story

As a user I want to be able to easily see details of the Mainnet Sims on fairground.wft. They should be distinguishable from existing incentives and include the Mainnet Sims branding.

## Acceptance Criteria

- [ ] I can see the Mainnet Sims clearly on the home page and they are distinguishable from other incentives
- [ ] I can click on each Mainnet Sim and the landing pages feature updated branding

## Tasks

- [x] Visual Design
- [ ] Review with Edo and Dan
- [x] Develop
- [ ] Test and set live

**Comment by bigfandavid** [comment]
Design of page can be viewed here: https://www.figma.com/file/QGqu1Yb5FD1NORc0mllKfH/Vega-Twitter%2FSocial-Assets?node-id=7709%3A773&t=GnTHiiammpQu6ozD-1

**Comment by goslingo** [comment]
Deploy preview here:
https://deploy-preview-240--optimistic-spence-370c3d.netlify.app/
