### ISSUE TITLE
Improve the Vega proposition statement on the landing page 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#407]
## The Chore

We are keen to improve the description of what Vega is / does on the landing page to be clearer

There has been lots of a-sync discussion in slack and comment threads in documents and [Nissa has drafted a potential revised version based on this discussion](https://docs.google.com/document/d/1DI5IEG_KNDVoDVkYQDdMWEXds_YU-dcW21nC-OXvNi4/edit). 

We are keen to have a short conversation to work out whether this draft is 'right' (or close enough that we could finesse it with copy editing), and if it's not 'right', understand why not and how we want to get to 'right' so we can then plan the work to get us there.

## Tasks

- [X] Penny to dig out the threads about it and share with team
- [X] Penny to schedule a call to discuss this
- [x] Rebecca to pick up with Ramsey & Barney / Nissa to see if we are in a position to decide on this
- [x] Penny to prep agenda for call
- [x] Create PR with revision and verify with Dave Mac if OK from a legal PoV 
- [x] Rebecca to get stakeholder feedback / agreement
- [ ] David to review the design layout and copy and propose any changes (if needed) considering the [related task to embed the coinlist video](https://github.com/vegaprotocol/vega.xyz/issues/396) - to be applied retrospectively
- [ ] Oli to implement
- [ ] Ben to test

## Approved copy

TOWARD A NEW ERA OF FINANCE

Vega is Web3’s native derivatives layer. Fully decentralised and optimised for permissionless market creation. Currently supports futures trading with an on-chain order book.

## Relevant Slack discussions: 

In #project-website-vega-xyz https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1670439443397339

## Relevant documents

Working Vega Positioning Doc: https://docs.google.com/document/d/1ikonar33xC42JNdpC6mLfITnX7x0OoJ1VQgayB4LjJY/edit

Blog post draft: https://docs.google.com/document/d/17fDQfofNipHgA4siwbjCWQeD3BGk7hriIzGT0XX4iKY/edit?usp=sharing

**Comment by pennyandrews** [comment]
This is currently blocked based on this Slack thread https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1674144963117069
