### ISSUE TITLE
Update roadmap timings

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#412]
## The Chore

As it is now 2023 H1 and trading is not yet enabled on mainnet, we need to update the roadmap with the latest anticipated timings.

## Tasks

- [ ] Change the default milestone to be Restricted Mainnet, not Alpha Mainnet (as we are not yet at Alpha Mainnet
- [ ] Ensure the 'Current status' label is on the Restricted Mainnet milestone, not Alpha Mainnet
- [ ] Update the Timing on Alpha Mainnet (suggestion for consideration in additional details below)
- [ ] Shift timings for all subsequent milestones back by a half year (v1 Mainnet 2023 H2, v2 Mainnet 2024 H1
- [ ] The current status callout needs to be updated (everywhere it appears, i.e. https://vega.xyz/use) to say trading launch H1 2023

## Additional details / background info

Suggestion for Alpha Mainnet timing revision from Barney (supported by Dan):
<img width="323" alt="Screenshot 2023-01-10 at 12 31 06" src="https://user-images.githubusercontent.com/47143694/211552405-243ca772-4be4-4c2a-b1e7-a7d1298bffc4.png">

Roadmap on Landing Page
<img width="1341" alt="Screenshot 2023-01-10 at 12 24 45" src="https://user-images.githubusercontent.com/47143694/211552099-b0e442d7-0dff-4b42-9079-bc7739470212.png">

Status Call Out
<img width="1418" alt="Screenshot 2023-01-10 at 12 27 59" src="https://user-images.githubusercontent.com/47143694/211552096-2f4f4e05-e78e-4fbc-a553-47ef483c559b.png">

**Comment by goslingo** [comment]
@pennyandrews ready for review:

https://deploy-preview-319--vega.netlify.app/
https://deploy-preview-319--vega.netlify.app/use
https://deploy-preview-319--vega.netlify.app/key-concepts
