### ISSUE TITLE
Incorporating the new Builders Club Project Tracker

### ISSUE THREAD

**Issue by proofofjake** [vegaprotocol/vega.xyz#430]
## The Chore

is it possible to get a link on [this](https://vega.xyz/builders-club) page to this new builders club projects homepage (https://vegaprotocol.notion.site/Builders-Club-Projects-Home-341102b14fb0461ba2685ffe5ee273eb), maybe in-between and in the same format as the buttons reading "apply now" & "meet us on discord"

## Tasks

- [ ] Make a button next to apply now
- [ ] Link button to the project homepage (https://vegaprotocol.notion.site/Builders-Club-Projects-Home-341102b14fb0461ba2685ffe5ee273eb)
- [ ] Text on button to read "Active Project Homepage"

## Additional details / background info

We need to consider the other content on this notion page as it could benefit from being on vega.xyz (as well as or instead of). And if we are working on the Builders Club page we should address the light mode issues (black text in header panel and vegabond white head on white background).

**Comment by pennyandrews** [comment]
Needs a little more discussion on how the team want to use notion v the web page
