### ISSUE TITLE
Get internal Vega people set up and able to effectively maintain the website

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#435]
## The Chore

As part of the plan to scale back investment on the website, we have a goal to ensure that there are **sufficient internal people at Vega that are able to make minor updates to website content**

## Tasks

- [ ] Agree a list of people that should be able to make updates to the website
- [ ] Get them set up and teach them how to do it
- [ ] Ensure there is sufficient documentation to support others doing the same
