### ISSUE TITLE
App identities

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#445]
## User Story

As a user
I want to be able to clearly identify / distinguish between Vega apps 
So that I understand what app I am already on / am going to / find the one I'm looking for 

## Acceptance Criteria

- I can visually see that the apps are different from one another i.e. on the [use the network page ](https://vega.xyz/use)of the website 
- I can associate a recognisable identify to each app 
- When I visit an app, I recognise it from the identify I saw on the [use the network page ](https://vega.xyz/use)of the website 
- When I have multiple Vega apps open in browser tabs, I can identify which tab is which app from the title AND FAVICON (because it represents the identity of the specific app visually)
- The app identifies work visually as a set
- The app identifies take into account how we also highlight visually when the app is pointing at the different networks (mainnet, fairground, other testnets e.g. validator testnet etc.)  
- We have considered whether/how the approach to the app identities applies to other channels like the governance forum, substack etc.)
- The app identities can be implemented on each app with minimal effort (i.e. they don't require any significant changes to the app layout or design)  

## Tasks

- [ ] Come up with visual identifies for each app 
- [ ] Get approval from Frontend Leads and wider Vega Leadership
- [ ] Create all required assets for implementation
- [ ] Create tickets for the work to implement the identities on the vega.xyz website and each app

## Current identities

**Current 'quick and dirty' identities on vega.xyz** 
![Image](https://user-images.githubusercontent.com/47143694/215739612-72df0873-b8df-48e9-bcfe-53136362df6b.png)

**Let's play which app is which**
![Image](https://user-images.githubusercontent.com/47143694/215743661-4aadf45a-e32f-4b4e-bd97-baaac1f0389c.png)
![Image](https://user-images.githubusercontent.com/47143694/215743917-253eb5fb-bc9b-40fb-877c-eec1ceeaf0b6.png)
![Image](https://user-images.githubusercontent.com/47143694/215743941-1348ff33-aae8-442e-9f5a-56bc714f7a0e.png)

**Console**
![Image](https://user-images.githubusercontent.com/47143694/215741473-0f537a82-3d01-433a-b5c8-2c0454a93ea8.png)

**Governance**
![Image](https://user-images.githubusercontent.com/47143694/215742392-1077d636-5adb-4244-8420-cd61c535674a.png)

**Explorer**
![Image](https://user-images.githubusercontent.com/47143694/215742466-02d2d20e-2fd0-4d6e-88d5-909916ee0f88.png)

**Wallet**
![Image](https://user-images.githubusercontent.com/47143694/215742828-7218a700-5dea-4ee6-847d-5ac74cf8f877.png)

**Docs**
![Image](https://user-images.githubusercontent.com/47143694/215742671-b86891b4-7608-4803-9df0-57052ad01227.png)

**Website**
![Image](https://user-images.githubusercontent.com/47143694/215742930-f836d57e-1104-494c-85c9-b1165d50ae9c.png)

**Forum**
![Image](https://user-images.githubusercontent.com/47143694/215742752-c52e0c2b-166c-415e-a705-913f575021d1.png)

**Substack**
![Image](https://user-images.githubusercontent.com/47143694/215742804-cb8d65d0-df12-4dea-accd-a4b3061ffddc.png)

**Comment by rebeccajsimmonds** [comment]
Slack threat https://vegaprotocol.slack.com/archives/C0473D9HN05/p1674832531741929
