### ISSUE TITLE
Remove direct from Console fairground links (in time for mainnet sims)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#448]
## The Chore

With the mainnet sims starting today, we need to take off the redirect from the links to Console / Trade futures (Testnet) on the website. We will be leaving it off now until console is deployed on Mainnet in line with the Alpha Mainnet release. 

## Tasks

- [ ] Remove redirects from 'Console' and 'Trade futures (testnet)' links on vega.xyz
- [ ] Review and deploy
- [ ] Test / update tests

## Additional details / background info

This was agreed in this thread https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1674081362797829 with @barney and @Matt
