### ISSUE TITLE
Wallet set up tutorial - Fairground (testnet) 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#451]
## Story

As a user
I want to see a tutorial of how to set up a Vega wallet on Fairground (testnet)
So that I feel supported in doing so, am more likely to get it right first time and have a good experience as a result

## Acceptance Criteria

- [ ] I can see and link to a video tutorial from the https://vega.xyz/wallet page of the website (perhaps near the 'How to use' section)
- [ ] I can see what network this tutorial is relevant for 

## Tasks

- [ ] Decide what details to show and where on the page to link to the tutorial
- [ ] Design how this will look on the page (as needed)
- [ ] Implement
- [ ] Test
- [ ] Release

## Additional details / background info

Slack thread from Edo sharing that a video tutorial has been created and shared on Twitter https://vegaprotocol.slack.com/archives/C02KSKW6Y3F/p1675253167005199

Link to video tutorial on YouTube channel for FAIRGROUND https://www.youtube.com/watch?v=fFmLQeQUa1k

**Comment by rebeccajsimmonds** [comment]
@goslingo @bigfandavid the links above are the target video's for this card. 

We will need to create a link or a thumbnail on https://vega.xyz/wallet/ to link to it.
