### ISSUE TITLE
Wallet page improvements

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#501]
As a user
I want to understand what I need a vega wallet for and easily identify the version of the vega wallet I need to use based on the network(s) I will primarily be using it with
So that I feel confident that Vega wallet is trustworthy and can download and install the app I need quickly and easily and avoid unnecessary compatibility issues / the need to regularly up/down grade to different versions AND that there is ultimately less of a barrier to trying out trading or governance on Vega

## Acceptance Criteria

These first three should already be covered by this ticket https://github.com/vegaprotocol/vegawallet-desktop/issues/557:
- [ ] There is a primary CTA to download the mainnet optimised vegawallet version 
- [ ] There is a secondary CTA to download the testnet optimised vegawallet version
- [ ] There is a tertiary CTA to explore all vegawallet releases on github

- [ ] There is content to help users understand what the vegawallet is for and how you use it
- [ ] The wallet proposition / key features we've landed on are prevalent on the landing page on the website
- [ ] There is content that informs users that Vega is an alpha stage software and so there are inherent risks in using it, but reassures that there are features and a team in place to make it as safe and reliable as possible etc. 
- [ ] The links to the latest official releases of the two versions of the wallet software (vega wallet, fairground wallet) are dynamically updated - no manual updates are required as part of the release process (this is already the case for mainnet, but not for fairground)
- [ ] The CTAs to download the wallet adopt the same visual treatment as the wallet app does to show network optimisation i.e. black for maininet, yellow for fairground
- [ ] Any images or videos on the get the vega wallet page should reflect the appropriate version of app based on the context of the content 

## Tasks

- [ ] Create more detailed sketch and define content
- [ ] Review with stakeholders
- [ ] Visual Design
- [ ] Implement
- [ ] QA Test
- [ ] Release

## Rough Sketch (will need to be updated when this work is planned)
![Website (vega xyz) - Vega wallet page refresh](https://github.com/vegaprotocol/vega.xyz/assets/46783148/ce290a90-59cc-4377-8cf6-27033ae0e335)

## Epic

This story is part of a bigger epic to **[Improve the user experience around software to network compatibility](https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764549808396986&cot=14)**. 

![Wallet - Frame 6](https://user-images.githubusercontent.com/47143694/229140288-2eaefbfa-8420-4f6a-8d31-8f0e41ab2d46.jpg)

This is the full list of tickets that make up the epic:

- vegaprotocol/vegawallet-desktop#557
- vegaprotocol/vegawallet-desktop#607
- vegaprotocol/vegawallet-desktop#610
- vegaprotocol/vegawallet-desktop#611
- #501

**Comment by rebeccajsimmonds** [comment]
@goslingo here is the link to the new How to set up a vega wallet video 

https://www.youtube.com/watch?v=NNhs01_AtPQ&list=PLtgXvHMJ2nYKm3eKoc77s-78oyS_yj7rq&index=1
