### ISSUE TITLE
Create new headline stats for homepage

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#509]
Jon needs to work out how we get the data

## Story

As a user of the website
I want to see a bunch of awesome stats related to trading on the homepage
So that I am greatly excited by Vega and its potential

## Acceptance Criteria

- [ ] I can view the Total Volume in USD 
- [ ] I can view the number of markets on the network
- [ ] I can view the number of unique users on the network 
- [ ] I can view the total value locked (TVL) on the ERC20 bridge
- [ ] I can view the current blocktime on the network
- [ ] Until we say so the CURRENT data is shown on the new format with 5 tiles 

## Tasks

- [x] Explore and sketch > DONE 
- [x] Team and stakeholder review > DONE
- [x] Visual Design > DONE
- [x] Team review > DONE
- [x] Define how to source this data

## Sketch
https://www.figma.com/file/BBhOooHYuME6g3m7mN9QMo/Landing-Page-Q2-2023?node-id=1901-10365&t=elvkV13oVn1jYjTf-0

## Additional details / background info
Below is how to source the data you need for each of the above.

Volume 
1. Query /api/v2/rewards/epoch/summaries
2. Filter for `epoch` = current epoch
3. Filter for `ACCOUNT_TYPE_FEES_INFRASTRUCTURE`
4. For the `amount` given for each `assetId` retrieve the value of `decimals` from the [assets API](https://api.vega.community/api/v2/assets)
5. Derive the "human readable amount" as `amount` / 10^ `decimals`
6. Divide each human readable amount by network parameter `market.fee.factors.infrastructureFee`
7. Use the Coingecko API at https://api.coingecko.com/api/v3/simple/price?ids=vega-protocol,tether,usd-coin,weth&vs_currencies=usd&include_last_updated_at=true
8. Multiply each value by the corresponding `usd` value in the API above (Use coingecko API key mapping table below to identify the relevant CCY pair) 
9. Add these up to get the Total Volume in USD

[Coingecko API mapping file](https://docs.google.com/spreadsheets/d/1PrVEnUAqRSof2BhWKZSFo5JaBIvVjDrZmptaMvKJ3xc/edit#gid=0)

NB. Whenever a new asset is added we will need to update the mapping table to include the new pair, and amend the coingecko query URL to include the new pair we need to retrieve.  I will add this to the asset creation governance support process. 

Total Markets
- Call the markets list API: `/api/v2/markets`
- Count all markets where `state` = `STATE_ACTIVE` or 'STATE_SUSPENDED'

Users
- Query `/api/v2/margin/levels` (This shows the margin level for every party on every market on Vega)
- Filter for `timestamp` > `/time` - `30 days` (using the [Vegatime API](https://docs.vega.xyz/mainnet/api/rest/core/core-service-get-vega-time) minus 30 to get any record in last month)
- Count distinct `partyId`

TVL
Confirming with Danny if there is any better approach here, but in my view the goal here is 1. Ease, 2. Consistency with Defi Llama so we dont look silly.  So with that in mind I suggest we connect to Defi Llama!
- Query `https://api.llama.fi/tvl/vega-protocol`
- Return the TVL value!

Blocktime 
Is already on the website currently so use that

**Comment by JonRay15** [comment]
Updated all original description to be accurate
