### ISSUE TITLE
Create market tiles on homepage

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#510]
## Story

As a user
I want to see some of the top markets on vega
So that I can see which interesting markets exist and can navigate to them easily 

## Acceptance Criteria

- [ ] I can see market tiles
- [ ] I can click on those tiles to launch console (via an interstitial page) 
- [ ] I can click on buttons to sort those tiles by a few factors

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design
- [x] Team review
- [x] Define how to source data for tiles

## Sketch

![image](https://user-images.githubusercontent.com/89918817/231997995-294cb13a-0d06-45b6-b472-9cfcb17211df.png)

## Additional details / background info

Assumption: Ciaran is already building a service to retrieve data from the APIs to display on the LP Dashboard on the website.  This service should already have most of the data we need, and shoudl be extended to provide extra data if we need it.  I am basing this ticket on exactly the data that is shown in the mockup above.

**Data tiles contain** 

**Market Name**
Should be available on markets API and is definitely in the LP Dashboard already

**Leverage**
DO NOT SHOW THIS

**24h Volume**
Is definitely on the LP dashboard already 

**Last Price**
Is definitely on the LP dashboard already 

**Price change in 24h**
Is definitely on the LP dashboard already 

**Price spark line**
There is a component that is already used in Console in the market dropdown that we need to make sure can be used by the website.

![image](https://user-images.githubusercontent.com/89918817/232001078-f0d0718f-7f3c-442d-a562-94552bfeb33d.png)

**Sorting**
The top X markets should be shown (based on however many David is aiming for on different break points).
The parameters to sort by are:

1. Top Volume = Based on 24h volume defined above 
2. Top Gainers = Highest positive price change in 24h defined above
3. Top Losers = Highest negative price change in 24h defined above
4. New Markets = Pretty sure this will be on the LP dashboard work because we have an "Age" in that.....I believe it should be sourced from the Open Timestamp on the markets API (see below), where we would show the ones where that timestamp is the most recent.

"marketTimestamps": {
            "proposed": "1680252546069151623",
            "pending": "1680252626005118784",
            "open": "1680599541329449508",
            "close": "0"
          },

**Comment by JonRay15** [comment]
On the assumption that for now you can park the leverage question, the rest of this ticket is ready for dev as we discusssed last week. 

I am following up in parallel on the leverage question and IF it comes into scope we can add it later.

**Comment by JonRay15** [comment]
Barney has confirmed we can remove leverage. so this ticket is ready for dev now.

https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1681745840570499?thread_ts=1681724747.758009&cid=C02KUFHDYAC
