### ISSUE TITLE
Move existing headline stats into new homepage format 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#512]
## Story

As a user
I want to see the headline stats in a slightly different format
So that I am happy 

## Acceptance Criteria

- [ ] I can see number of validators
- [ ] I can see total staked $VEGA
- [ ] I can see current epoch
- [ ] I can see blocktime
- [ ] When this component is updated with new data when trading is live, there will be 5 stats and so the layout needs to adapt automatically from 4 to 5 when added

## Tasks

- [ ] Understand whether this service is going to break as apis move to v2 with launch
- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Define where to get number of stakers

## Sketch

![image](https://user-images.githubusercontent.com/89918817/232012348-a91b87cf-9214-4857-a0d6-fb524f558aa7.png)
