### ISSUE TITLE
Governance page improvements for voting

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#526]
## The Chore

Tweak content on the governance page to prioritise voting over the lifecycle content. 

## Tasks

- [x] Move up the calls to action (three boxes) 
- [x] Rename with verbs i.e. "Forum" becomes "Discuss proposals", Governance becomes "Vote"
- [x] Put into sequence: Discuss proposals, Submit a proposal, Vote
- [x] Update "Discuss proposals" description to: Read initial proposals and get involved in the discussion before the proposal goes to vote.
- [x] Update "Vote" description to: Review and vote on governance proposals.
- [x] Move imagery further down the page
- [x] Move "get started voting" section to above "governance lifecycle" 

## Sketch
![X Platform UX - Frame 19](https://user-images.githubusercontent.com/46783148/235761994-a8a833a3-5c7f-4ff6-b441-eb89c69a2af1.jpg)

## Additional details / background info

Make a proposal description to be updated as part of 
https://github.com/vegaprotocol/frontend-monorepo/issues/2205

**Comment by pennyandrews** [comment]
Ready for your viewing pleasure @ckpringle https://deploy-preview-547--vega.netlify.app/governance
