### ISSUE TITLE
Understand likely return from Staking

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#542]
## Story

As a potential staker on Vega 
I want to understand the likely return on my investment 
So that I can make a decision / comparison of staking on Vega vs. others

## Acceptance Criteria

- [ ] There is a way to understand the sort of return you can expect from staking on Vega on the website and governance app (which could be showing just the fees paid out last epoch for example)
- [ ] I can understand there is a difference between treasury rewards and infrastructure fees included in that return 
- [ ] It is clear where the numbers have come from and / or how the return has been calculated 

## Tasks

- [ ] Review / agree best approach for what we want to show to help people understand return on staking (see sketches and maths from earlier iterations below)
- [ ] Get the maths right
- [ ] Update sketches
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Implementation
- [ ] Team review
- [ ] Etc.

## Old sketch
<img width="1234" alt="Screenshot 2023-05-10 at 09 27 26" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/27682308-1af7-45d5-9050-495ec78bfb1a">

## Existing design work 

https://www.figma.com/file/AlPkMuAwHtfSQCeaZRrpkv/Develop?type=design&node-id=1804-2023&t=Fo05xfvVh7S14H9f-0

## Additional details / background info

Initial method for calculating APY: 

```
import { useEffect, useState } from 'react'

export const useStakingApy = () => {
  const [error, setError] = useState(false)
  const [data, setData] = useState[{}](https://app.slack.com/client/T8WS6EKV4/null)(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.all([
      fetch(`[https://api.vega.xyz/epochs`](https://api.vega.xyz/epochs%60)),
      fetch(
        `https://api.vega.xyz/parties/603f97f4499634372cc0fe50f4a0834bdf662d0b54c15b0bac5832367bae239b/rewards`
      ),
    ])
      .then((responses) => {
        return Promise.all(
          responses.map(function (response) {
            return response.json()
          })
        )
      })
      .then(function (data) {
        const latestEpoch = data[1].rewards[0].epoch
        let totalRewards = 0
        let percentageOfTotal = 0

        // Find the total rewards for the latest epoch
        for (const reward of data[1].rewards) {
          if (reward.rewardType === 'ACCOUNT_TYPE_GLOBAL_REWARD') {
            totalRewards = reward.amount
            percentageOfTotal = reward.percentageOfTotal
            break
          }
        }

        const totalRewardsThisEpoch =
          totalRewards / Math.pow(10, 18) / (percentageOfTotal / 100)

        // Find the total staked on network
        let stakedTotal = 0
        data[0].epoch.validators.forEach((validator) => {
          let validatorTotal = parseInt(validator.stakedTotal)
          stakedTotal = stakedTotal + validatorTotal
        })

        stakedTotal = stakedTotal / Math.pow(10, 18)

        // Calculate APY
        const apy = ((totalRewardsThisEpoch / stakedTotal) * 365 * 100).toFixed(
          3
        )

        setData({
          apy: apy,
          totalRewardsThisEpoch: totalRewardsThisEpoch.toFixed(0),
        })
        setLoading(false)
      })
      .catch(function (error) {
        setLoading(false)
        setError(error)
      })
  }, [])

  return { data, loading, error }
}
```

**Comment by pennyandrews** [comment]
We will need support from someone else at Vega to either provide the APIs and calculations for us to be able to calculate this client side OR someone backend to create a small service to do this calculation for us to just consume the resulting data.

However, this ticket looks like this is now redundant based on the conclusions of that thread: https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1684771713779919?thread_ts=1684770912.172739&cid=C02KUFHDYAC
