### ISSUE TITLE
Update market creation links to point to mainnet

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#553]
## The Chore

Now that Alpha Mainnet is live, the governance process for asset creation is underway and once that is completed we will be ready to move into Market Creation and will need to enable market creation on mainnet. Therefore we will need to update content and links on the Market Creation page to link to mainnet. We don't want to do this before asset creation is complete as it won't be possible to create markets until then. 

### Market Creation Lifecycle

**Phase 1 Sense check**

- [ ] Update [Start a topic on the forum (Testnet)](https://community.vega.xyz/c/fairground-testnet-governance/32) to [Start a topic on the forum](https://community.vega.xyz/c/governance/market-proposals/28)
- [ ] Update [See what markets exist already (Testnet)](https://console.fairground.wtf/#/markets) to [See some example markets (Testnet)](https://console.fairground.wtf/#/markets)

**Phase 2 Formalise**

- [ ] Update [Read the docs to make a proposal (Testnet)](https://docs.vega.xyz/testnet/tutorials/proposals/new-market-proposal) to [Read the docs to make a proposal](https://docs.vega.xyz/mainnet/tutorials/proposals/new-market-proposal)
- [ ] Update [Check out the forum (Testnet)](https://community.vega.xyz/c/fairground-testnet-governance/32) to [Check out the forum](https://community.vega.xyz/c/governance/market-proposals/28)

**Phase 3 Submit**

- [ ] Update [Read the docs to make a proposal (Testnet)](https://docs.vega.xyz/testnet/tutorials/proposals/new-market-proposal) to [Read the docs to make a proposal](https://docs.vega.xyz/mainnet/tutorials/proposals/new-market-proposal)

**Phase 4 Get Voting**

- [ ] Update [Vote for proposals (Testnet)](https://token.fairground.wtf/governance/) to [Vote for proposals](https://governance.vega.xyz/proposals)

**Phase 5 Attract Liquidity**

- [ ] Update [Read the docs about liquidity provision (Testnet)](https://docs.vega.xyz/testnet/tutorials/committing-liquidity) to [Read the docs about liquidity provision](https://docs.vega.xyz/mainnet/concepts/liquidity/provision)

**Phase 6 Launch Market**

No changes
