### ISSUE TITLE
Hook up Rewards data now alpha mainnet is live with active markets

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#555]
## The Chore

We have three key rewards stats being showcased on the [Rewards page of the website](https://vega.xyz/rewards) (Trading, Liquidity Provision, Market Creation} that are currently marked as 'coming soon'. Now that Alpha Mainnet is live and we have markets live and people earning rewards, it would be great to hook these stats up to show real data 

<img width="1428" alt="Screenshot 2023-05-11 at 12 36 45" src="https://github.com/vegaprotocol/vega.xyz/assets/47143694/d9f98380-c39b-4d6b-b86e-19ed30b42ab3">

## Tasks

- [ ] Establish what APIs we need to use to get the data
- [ ] Hook up the stats to the relevant APIs to get the data
- [ ] Review and test
- [ ] Add automated regression tests
- [ ] Release
