### ISSUE TITLE
Make audits visible on the website

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#612]
## Story

As a Nimble Fund / Prop Shop
When researching Vega, I want to know about the audits that Vega has been subject to 
So that I can get a feel for how robust the software is and how serious Vega are as a project

## Acceptance Criteria

- [x] I can understand what Audits have been conducted on Vega  
- [x] I can understand who has conducted each audit 
- [x] I can understand when each audit took place (at least month and year) 
- [x] I can find out more about the outcomes of the audits

## Sketches

https://miro.com/app/board/o9J_lnkofoQ=/?moveToWidget=3458764557104849359&cot=14

<img width="990" alt="Screenshot 2023-06-14 at 15 57 47" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/0360f1e1-59b3-44be-b88c-db580a144476">

<img width="331" alt="Screenshot 2023-06-14 at 15 58 38" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/fa9361b4-42a9-4946-8465-ca5c80760c05">

## Tasks

- [ ] Collate information about the audits Vega has conducted / has planned
- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Implementation
- [ ] Test
- [ ] Release

## Background

[Rocket Pool](https://rocketpool.net/#security) stated as a good example
<img width="1364" alt="Visibility of Audits" src="https://github.com/vegaprotocol/vega.xyz/assets/47143694/5a09d27f-fea7-4466-9670-44afcd60cfda">

Rocket Pool link to the detailed audit document published by the auditor https://consensys.net/diligence/audits/2021/04/rocketpool/

**Comment by rebeccajsimmonds** [comment]
These are the current audits we have for the smart contracts, they can also be found here: https://github.com/vegaprotocol/MultisigControl/tree/develop/audit

The full was the audit of all the contracts, the second (decentralised limits) was the latest where we updated the contract to allow people to be able to whitelist themselves to deposit more than the limits (edited)

**Comment by pennyandrews** [comment]
@vegaprotocol/research can you please add the info for the third audit, ta

**Comment by goslingo** [comment]
@rebeccajsimmonds 

Deploy preview:
https://vega-lnk5m7g92-vegaprotocol.vercel.app/

**Comment by goslingo** [comment]
@JonRay15 Deploy preview:

https://vega-4epnasvzp-vegaprotocol.vercel.app/

**Comment by JonRay15** [comment]
Change the intro text where it says "The Vega codebase has been audited by the best"

To 

"Vega protocol is still in alpha and changing rapidly.  As a result not all the code is currently audited, but where possible top quality auditors have been already been engaged to review the more stable parts of the protocol."

**Comment by rebeccajsimmonds** [comment]
@JonRay15 what do we want this text to say now that Palazzo is going live and (I believe) that is when we are out of Alpha

**Comment by rebeccajsimmonds** [comment]
@edd could you make the copy change above 

Vega protocol is still in alpha and changing rapidly. As a result not all the code is currently audited, but where possible top quality auditors have been already been engaged to review the more stable parts of the protocol.
