### ISSUE TITLE
Consume price data from Coingecko to standardise Total Volume calc

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#635]
## The Chore

We need a feed / API call / webservice or something that consumes prices from Coingecko for any settlement assets we have in Vega.  I'm assuming something like [this](https://www.coingecko.com/en/api), but we can explore options.

## Tasks

- [ ] Get the list of settlement assets from `/api/v2/assets` where `"status": "STATUS_ENABLED"`
- [ ] For each of these retrieve a price from the Coingecko API somehow (based on `symbol` or `erc20 contractAddress`)
- [ ] Store this somewhere as we might use it a few places 
- [ ] Immediate task is to use this to enhance https://github.com/vegaprotocol/vega.xyz/issues/509 
- [ ] Currently that task filters for only USDT and USDC, but once the above is available we shoudl convert all asset balances into USD equivalent and sum them up to get the Total Volume
- [ ] We may then use this elsewhere too

## Additional details / background info
This change will not be needed until we have markets settling in non-USD equivalent assets.  We have a live proposal for WETH so if someone built markets on that it would suddenly be needed.

**Comment by pennyandrews** [comment]
[@fryd](https://vegaprotocol.slack.com/team/U01R8SLMF3R)
 has built some sort of feed from Coingecko for prices for his monitoring. Potentially we can steal this and then we'd be able to convert our total volume numbers All you need to do is call this API https://api.coingecko.com/api/v3/simple/price?ids=vega-protocol,tether,usd-coin,weth&vs_currencies=usd&include_last_updated_at=true

**Comment by JonRay15** [comment]
This will become redundant if Oli makes the changes on the existing ticket as I have just requested

**Comment by pennyandrews** [comment]
The ticket @JonRay15 is referring too is https://github.com/vegaprotocol/vega.xyz/issues/509 which is in progress so closing this. Jon, please verify this is correct, thanks
