### ISSUE TITLE
Updates for programmatic trading 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#670]
## The Chore

We need to make some updates to the website for programmatic traders to make the signposting clearer.

## Tasks 

- [x] Update "Vega's APIs" heading on the home page to "Programmatic trading on Vega"

<img width="792" alt="Screenshot 2023-06-15 at 14 30 32" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/793402da-515a-47fb-88d7-d1821e48685d">

- [x] Update "Market make and provide liquidity using the APIs" heading on https://vega.xyz/market-making-and-liquidity-provision to "Programmatic trading on Vega"
- [x] Update subheading from "Anyone can become a market maker..." to "Enabled through rich CEX-style APIs  for deployment of market making, liquidity provision, and directional trading strategies"

<img width="793" alt="Screenshot 2023-06-15 at 14 33 37" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/f5d59fda-0fea-4962-be1d-9faa4aa2a9e4">

- [x] Update URL of this page https://vega.xyz/market-making-and-liquidity-provision to https://vega.xyz/programmatic-trading
- [x] Update navigation links 
- "Programmatic trading" (appears under "use vega" : "trading" subheading, replacing "market make and provide liquidity...")
- Add to under "develop": "build"

<img width="711" alt="Screenshot 2023-06-15 at 14 45 54" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/c1db1b5a-e8e2-41ff-83a7-2fb3ebcd84c9">

- [x] Change description of "Market Makers" to: "Users who place static or pegged order limit volume on the book will receive 0.02% of the trade value when an incoming trade matches their order."

- [x] Change description of "Liquidity providers" to: "Users willing to commit a set bond amount to help ensure a market's liquidity additionally earn a liquidity provision fee set per market."

- [x] Change heading "Get started" to "Starter kit" 

- [x] Move "Prerequisites" to step 1 of the starter kit (Vega Wallet being step 2 now) 

- [x] Update layout of Prerequisites to reduce spacing / prominence 

<img width="794" alt="Screenshot 2023-06-15 at 14 39 48" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/7a774c25-1e85-4016-b934-57d4e72b42d8">

- [x] Change "Get a wallet" to "Vega Wallet" heading (now step 2) 

- [x] Change "Check out the APIs" to "Explore the APIs" heading (now step 3)

- [x] Change "Follow a tutorial and get code snippets" to "Tutorials and code snippets" (now step 4)

## Sketch
![X Platform UX - Updates for programmatic trading #670](https://github.com/vegaprotocol/vega.xyz/assets/46783148/054c2bcb-4cb2-45c3-9187-e81cddd1ca09)
