### ISSUE TITLE
Update roadmap content to reflect Deployment 1

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#687]
## Story

As a Vega user
I want to know what features have been recently released and what's coming next
So that I can see there is lots of active software development

## Acceptance Criteria

- [ ] I can see the latest deployment reflected on the roadmap module
- [ ] I can see an accurate reflection of the features planned to come later this year on the roadmap module
- [ ] The detailed github roadmap is an accurate reflection of the planned features and deployments

## Tasks

- [ ] Sketch and finalise copy
- [ ] Team and stakeholder review
- [ ] Implementation 
- [ ] Testing
- [ ] Release

**Comment by JonRay15** [comment]
Oer #840 we are now removing this entirely  ... so closing.
