### ISSUE TITLE
Steps to be able to trade on website

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#729]
## Story

As a user new to Vega
I want to understand the steps needed before I can trade
So that I understand what to expect if I start from the website 

## Acceptance Criteria

- [ ] I can see the onboarding steps to trade i.e. get and connect a Vega wallet, deposit assets from your Ethereum wallet based on the market you want to trade, open a position
- [ ] There are links from here to get a wallet and view markets on console

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
