### ISSUE TITLE
Show liquidity provision network parameters on liquidity dashboard

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#732]
## Story

As a potential liquidity provider
I want to understand what would be required of me
So I can make an informed decision about providing liquidity on Vega

## Acceptance Criteria

- [ ] I can see all network parameters relevant to liquidity provision on Vega
- [ ] Where relevant these are pulled onto the LP tiles on the homepage

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info
- [Barney on Slack](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1689169227474159?thread_ts=1689162667.366119&cid=C8WS7M50E): "You would probably want to show the SLA and other related parameters so that potential LPs know what they have to sign up to to be an LP on that market"

**Comment by JonRay15** [comment]
Dupe of #4552
