### ISSUE TITLE
Show total fees accrued by LPs on liquidity dashboard

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#733]
## Story

As a potential liquidity provider
I want to see examples of returns
So I can make an informed decision about providing liquidity on vega

## Acceptance Criteria

- [ ] I can see the total Liquidity Provision fees paid out over the lifetime of each market

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info
- Ticket for the same task in console: https://github.com/vegaprotocol/frontend-monorepo/issues/4317

**Comment by JonRay15** [comment]
I heavily suspect that right now this will require looking in the ledger entries. This will not be viable due to row count. 

This should not be supported until Core provide some sort of summary API for that - which is already ticketed on their board as #7393

**Comment by JonRay15** [comment]
Think this is actually now very easy and that @MadalinaRaicu has already done it on Console. 

We should be able to copy that I think. Will ask her.
