### ISSUE TITLE
Link to Vega Wallet browser extension with very deprioritised linking to desktop wallet

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#745]
## The Chore

We need to update the wallet page in line with release of the browser extension for mainnet. This involves changing the calls to action section of the website here https://vega.xyz/wallet#overview

## Acceptance Criteria 
- [x] Primary calls to action are updated on the wallet page to the browser extension for both mainnet and fairground 
- [x] Text should say Get the Vega Wallet (Alpha) then both Chrome & Firefox icons
- [x] The link used is based on the browser being used to access the site i.e. for chrome, link to https://chrome.google.com/webstore/detail/vega-wallet/nmmjkiafpmphlikhefgjbblebfgclikn, for firefox link to https://addons.mozilla.org/en-GB/firefox/addon/vega-wallet/
- [x] There is a secondary call to action for those looking for the desktop wallet software
- [x] There is a link to our supported browser documentation https://github.com/vegaprotocol/vegawallet-browser/issues/360
- [x] There is a link to the github project for the browser extension https://github.com/vegaprotocol/vegawallet-browser

In the event that a user is not using Chrome or Firefox
- [x] The call to action is split and the user can choose either to get the chrome or the firefox extension
- [x] There is copy explaining that while we do not have an official version for your browser, you can continue at your own risk along with a link to our supported browser documentation https://github.com/vegaprotocol/vegawallet-browser/issues/360

If I select to get the desktop wallet software
- [x] I can see a warning that the software is in maintenance mode, that I should use the browser extension unless I am looking for multi wallet support or building something using our APIs
- [x] There is a call to link to the github releases for the desktop wallet 
- [x] I can dismiss the warning easily to go get the browser extension instead

## Sketch 

https://miro.com/app/board/uXjVM2wamp8=/?moveToWidget=3458764559581495030&cot=14

<img width="1488" alt="Screenshot 2023-07-21 at 09 22 54" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/89df34da-7755-4175-8acb-0183b971d245">

<img width="1483" alt="Screenshot 2023-07-21 at 09 23 03" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/fcaa4359-6ef1-4488-bdd4-445a3faac764">

<img width="1628" alt="Screenshot 2023-07-21 at 09 59 28" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/50a42c54-9918-45fe-91c1-50edc7fbd8ac">

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by JonRay15** [comment]
Some additional ACs based on rework because Calum went a bit rogue and has overly de-emphasised the desktop wallet

1. In the main CTA we should have the white primary button for browser, and then beneath it we should have the de-emphaises black button for the Desktop wallet and clicking it should trigger the same dropdown for OS that it does currently.
2. Remove the link that says "looking for the desktop wallet"
3. Replace it with a new link that says "Want to test on fairground?" which will hyperlink to lower on the screen to a new section....
4. Add a new section that duplicates the "DEVELOPERS" section at the bottom (shown below); suggest we actually put this BEFORE the developers section.  This section should be titled "Test on Fairground" and should include buttons to download the new fairground browser wallet AND the old desktop wallet (with the same OS dropdown).  If those sections need titles / text something simple like "Test with latest Browser Wallet" and "Test with legacy Desktop Wallet" would be fine.



![Image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/7f273adb-149f-47b9-a324-a91edab15556)

**Comment by goslingo** [comment]
https://vega-mh1std56p-vegaprotocol.vercel.app/wallet/

Awaiting the links for the mainnet browser wallet extensions.
