### ISSUE TITLE
Acknowledge perpetuals on the homepage

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#754]
## Story

As a visitor interested in Vega's status
I want to know what kinds of markets are live and active
So that I can understand Vega's offering and compare Vega to competitors

## Acceptance Criteria

- [ ] I can tell Vega supports perpetual markets
- [ ] Ideally, I can see evidence of recent activity in perpetual markets

## Tasks

- [ ] Homepage
  - [x] Metadata should change to "Futures & Perpetuals DEX"
  - [x] Strapline should become "Cash settled futures and perpetuals are now live on Vega's Alpha Mainnet"
  - [x] The markets tiles need will need to have a product type lozenge / text added to them to capture the product type (FUTR or PERP)... we have an implementation on the LP dashboard that could be copied
  - [x] We could add a filter for the markets for All / Perps / Futures with All being the default (there is also a pattern for this on the LP dashboard to copy)
- [x] On Apps & Tools on the Console tile change to "A dApp for trading cash settled futures and perps on the fully decentralised Vega network"
- [x] Accouncement banner should probably be updated to say "Perpetuals are now live on the Vega network, head to the [forums](https://community.vega.xyz/c/governance/25) to participate in community governance" or something.

## Sketch

![Image](https://github.com/vegaprotocol/vega.xyz/assets/1080322/4170131b-9c39-4900-ac94-d30e1dc6ec47)
