### ISSUE TITLE
Referral site landing page

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#800]
## Story

As a user
I want to understand a summary of the benefits of the Vega Referral scheme at a glance and how it works
So that I can use this to decide if it's something I want to participate in 

## Acceptance Criteria

- [ ] I can see a summary of how it works e.g. the top commission (referrer reward) %, the top % saving off of trading fees for referees, and how long it lasts for
- [ ] There is a prominent call to action to create a referral code 
- [ ] There is a prominent call to action to apply a referral code
- [ ] I can understand the tiers, their referrer reward %, trading fee discount %, running trading volume required, the number of epochs you need to be in a team to join the tier 
- [ ] I can understand that there is a max party volume per epoch, what it is capped at, and why (to prevent wash trading)
- [ ] I can understand terms for taking part in the programme

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch
https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764560265784550&cot=14

<img width="423" alt="Screenshot 2023-07-28 at 15 28 17" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/f23b434b-8eb0-4883-b994-c779f0f6fa02">

![Image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/b212f438-80ea-4e76-85eb-50c42c8d4e9f)

## Additional details / background info
Leaderboard is in a separate ticket #801

**Comment by JonRay15** [comment]
API ticket is now merged https://github.com/vegaprotocol/vega/issues/9255
