### ISSUE TITLE
Create a referral code on the referral site

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#802]
## Story

As a referrer / team maker
I want to create a referral code to refer traders to Vega
So that I can help build the Vega community and get rewarded

## Acceptance Criteria

- [ ] I can understand the steps to create a referral code 
- [ ] There is a way to connect my wallet if I haven't already
- [ ] When I have connected, there is a way to trigger a transaction to create a referral code
- [ ] If I have confirmed the transaction, I can see my shareable URL , fee discount % and referrer reward %
- [ ] There's an easy way to copy this to clipboard 

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764559935654829&cot=14
![Image](https://github.com/vegaprotocol/vega.xyz/assets/46783148/4ad6b2a1-9dd6-4211-b3e1-fa38aaf03ca8)
