### ISSUE TITLE
Apply referral code (referral site)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#810]
## Story

As a user who has received a team code / link
I want to easily apply it to my key
So that I can benefit from trading fee savings 

## Acceptance Criteria

- [ ] I can see the referral code I am applying
- [ ] I can see the discount I would receive on initial sign up 
- [ ] There is a call to action to apply the code
- [ ] There is a way to find out more about the referral scheme i.e. a link to the about content / landing page
- [ ] If the link that has been shared with me is *just* for a referral code and not a team, I can still see the information specific to that referral code 

When I select to apply the code 
- [ ] I can see I need to connect my wallet 
- [ ] I can see I need to get a wallet if I don't have one already 
- [ ] I can see that I need to confirm or reject a transaction in my wallet in order to apply the referral code i.e. there is text on the screen telling me to go check my wallet 
- [ ] When the code is applied to my key successfully, there is visual feedback, and I can understand where I can go to see my code at any time
- [ ] I can now see my referral code applied to the key I am connected with on the referral site 

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch
Miro https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764559935654831&cot=14

![Image](https://github.com/vegaprotocol/vega.xyz/assets/46783148/4ed8a9c8-7bd7-4ae8-92eb-0b0e8dfc13b6)

https://www.figma.com/file/SPSdqynG3Xk4RzBJ7NKpdi/Referrals?type=design&node-id=3166-5839&mode=design&t=5hNJGqp9HjVqPxaJ-0
