### ISSUE TITLE
Handle existing referral programme / team members (referral site)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#811]
## User Story 

As a user 
I want to understand that applying a referral code on this same key, will move team and impact my savings on trading fees
So that I can make an educated decision on what to do next 

## Acceptance Criteria 
- [ ] When a connected key already has a team / code applied, there is a way to see that
- [ ] I can see the effect changing to the new team / code will have on the savings i am currently seeing 
- [ ] There is a way to proceed to join the new team 
- [ ] When I select to join the new team, I am told that I need to now confirm or reject the transaction in my wallet
- [ ] Upon successfully moving team, I can see the new team details in my "connected" view of the referral site

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

## Additional details / background info
<img width="1748" alt="Screenshot 2023-07-28 at 16 08 15" src="https://github.com/vegaprotocol/vega.xyz/assets/46783148/30a9b440-4c69-429d-ba27-ba5afce79efc">

**Comment by JonRay15** [comment]
This is not possible with latest core implementation
