### ISSUE TITLE
Handle existing team creator

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#827]
## Story

As an existing team creator 
I want to understand that I cannot create another team with this key 
So that I know what to do next instead

## Acceptance Criteria

- [ ] I can see that I have already created a team / code on the key I have connected with 
- [ ] I can see that there is a way to disband my current team 
- [ ] I can understand the impact of this - i.e. I can see my current reward amount that I would be giving up 
- [ ] 
## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by JonRay15** [comment]
We can cover this as part of create team
